### ISSUE TITLE
Document local DNS resolution for Docker

### ISSUE THREAD

**Issue by danecreekphotography** [danecreekphotography/node-deepstackai-trigger#12]
Right now if you just clone the repo and run `docker-compose up` you have to use local IP addresses, rather than domain names, to access machines on the local network (e.g. a BlueIris server, MQTT server, etc.)

It would be nice to figure out how to enable this, and:

* Update the sample docker-compose.yml if necessary
* Document any Docker Desktop changes required to make this work

Docker Desktop for Windows and Mac both default to Google DNS resolution. Maybe that's all that's necessary to change?

**Comment by danecreekphotography** [comment]
Changing the Docker Desktop DNS entry to my local network DNS server didn't solve anything.

**Comment by rohankapoorcom** [comment]
I wonder if this is a limitation of docker for windows/mac vs native docker on linux. With a standard docker setup on linux (Ubuntu 16.04) - it automatically used the local DNS resolution from the host.

**Comment by danecreekphotography** [comment]
Thanks. It probably does "Just Work" and I was doing something else wrong. I this in my early days of Docker understanding. Just gotta find some time to confirm and then close it out!

**Comment by danecreekphotography** [comment]
Not needed anymore.
