### ISSUE TITLE
Test installing on Synology

### ISSUE THREAD

**Issue by danecreekphotography** [danecreekphotography/node-deepstackai-trigger#121]
See how it works and if there's anything that can make it easier

**Comment by danecreekphotography** [comment]
This doesn't work because Docker on Synology doesn't support secrets. Looks like I need a new fallback feature...

**Comment by danecreekphotography** [comment]
Done and works with the latest build.

**Comment by alexsahka** [comment]
> Done and works with the latest build.

How do you fixed this?

**Comment by danecreekphotography** [comment]
See the project wiki for information on [how to install on a Synology or Unraid server](https://github.com/danecreekphotography/node-deepstackai-trigger/wiki/Deploying-to-Synology-and-Unraid).

If you want the code changes check out the [pull request](https://github.com/danecreekphotography/node-deepstackai-trigger/pull/126).
