### ISSUE TITLE
Write a detailed installation guide

### ISSUE THREAD

**Issue by danecreekphotography** [danecreekphotography/node-deepstackai-trigger#150]
Something more than the quickstart, that goes step-by-step through creating a local directory, configuring the docker-compose.yml, and triggers.json file.

**Comment by Viksie** [comment]
#184

**Comment by TrunkMonk** [comment]
In addition to a detailed install guide, would it be possible to build out a web page to populate the settings.json, triggers.json  or other config files such as this website that generates answer files for Microsoft OS unattended deployments:  https://www.windowsafg.com/win10x86_x64_uefi.html

Ideally, the site would allow importing of existing .json files for modification and error checking

**Comment by danecreekphotography** [comment]
Technically? Yes, but it's not something I'm planning to do. I just don't have the time for it.

Editing in VSCode helps as the schema files result in auto-complete and tooltips.

**Comment by mist0706** [comment]
There is no documentation on how to use gpu acceleration. For example the gpu tag should be used on the image and the runtime needs to be added

**Comment by danecreekphotography** [comment]
Closing old issues.
