### ISSUE TITLE
Support configuration files in default Docker volume mount location

### ISSUE THREAD

**Issue by Viksie** [danecreekphotography/node-deepstackai-trigger#161]
Any reason the config files is not rather held within a docker defined volume, i.e. /var/lib/docker/volumes/trigger/_data

**Comment by Viksie** [comment]
I understand it's not a case of getting the config files in the container as it's a case of keeping the config files out of the container. Thus, should you destroy the container, the configs remain untouched and makes upgrades so much easier.

**Comment by danecreekphotography** [comment]
It's the same either way: a volume mount and a local file system mount both store the files outside of the container and they are maintained through container rebuilds.

**Comment by Viksie** [comment]
Why do I feel so confused with that statement  .... 

My progress is reflected at [Issue144](https://github.com/danecreekphotography/node-deepstackai-trigger/issues/144)
