### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by Viksie** [danecreekphotography/node-deepstackai-trigger#166]
This project has had me already loose two days' sleep and I still do not wish for the infatuation to come to an end.

I'm not a programmer and know there's surely quite a steep learning curve ahead in becoming a valued supporter / maintainer.

As such, where would a newcomer start ? At the home pages of:

1. Github
2. NodeJS and
3. Docker

or is there a more specific course to get on-board quicker ?

**Comment by danecreekphotography** [comment]
See my comment on your latest update in #144. You actually appear to be up and running at this point and just need to make sure the trigger configuration file is set up correctly.

There is full documentation on how the triggers get configured on the wiki: https://github.com/danecreekphotography/node-deepstackai-trigger/wiki/Defining-triggers. The [sample file](https://github.com/danecreekphotography/node-deepstackai-trigger/blob/master/sampleConfiguration/triggers.json) is a good starting point for the common case of wanting to call BlueIris to tell it to start recording. It shows the pattern for setting up triggers and you just have to replace the values with ones appropriate for your configuration. 

There is no need to know about github or NodeJS to run this. Docker knowledge helps, and Portainer adds a layer of complexity that frankly adds more confusion in my view. Regardless, as mentioned over in #144, you do appear to have the system up and running you just need to test with the right image files and/or modify `triggers.json` to fit your actual use case.

**Comment by Viksie** [comment]
Sorry, this query was not related to the actual installation, but orientated at the knowledge required for a newb to be able to become a contributor of code fixes and feature in the near future.

**Comment by danecreekphotography** [comment]
Ah, I got it. A knowledge of NodeJS and TypeScript is a must, that's the framework and language used to write all the code for this.
