### ISSUE TITLE
node-telegram-bot-api deprecation warning

### ISSUE THREAD

**Issue by Viksie** [danecreekphotography/node-deepstackai-trigger#174]
From logs:

[Telegram manager] Sending message to -10xxxxx
node-telegram-bot-api deprecated Buffers will have their filenames default to "filename" instead of "data". See https://github.com/yagop/node-telegram-bot-api/blob/master/doc/usage.md#sending-files for more information on how sending files has been improved and on how to disable this deprecation message altogether. at bundle.js:333:34074
node-telegram-bot-api deprecated In the future, content-type of files you send will default to "application/octet-stream". See https://github.com/yagop/node-telegram-bot-api/blob/master/doc/usage.md#sending-files for more information on how sending files has been improved and on how to disable this deprecation message altogether. at bundle.js:333:34074

**Comment by danecreekphotography** [comment]
That's weird, I've never received that :( Can you please try setting this environment variable on the trigger docker container and see if the warning goes away: `NTBA_FIX_350`. Just set it to any string, like `"true"`.

**Comment by danecreekphotography** [comment]
I see this in my local deployment of the production builds as well.

```
trigger_1       | Sat, 13 Jun 2020 18:14:06 GMT node-telegram-bot-api deprecated Buffers will have their filenames default to "filename" instead of "data". See https://github.com/yagop/node-telegram-bot-api/blob/master/doc/usage.md#sending-files for more information on how sending files has been improved and on how to disable this deprecation message altogether. at bundle.js:419:34091
trigger_1       | Sat, 13 Jun 2020 18:14:06 GMT node-telegram-bot-api deprecated In the future, content-type of files you send will default to "application/octet-stream". See https://github.com/yagop/node-telegram-bot-api/blob/master/doc/usage.md#sending-files for more information on how sending files has been improved and on how to disable this deprecation message altogether. at bundle.js:419:34091
```

**Comment by danecreekphotography** [comment]
This should be fixed now @Viksie, thanks for reporting it. It's available in the `dev` tag image at the moment and I'll put it in the `latest` image when I release some other stuff hopefully tomorrow.
