### ISSUE TITLE
Failed to call Deepstack 

### ISSUE THREAD

**Issue by Viksie** [danecreekphotography/node-deepstackai-trigger#175]
First image analysed and triggers fired correctly.

Second attempt resulted in :

[Trigger Cat Cam] /aiinput/Cat_20200523-075000.jpg: Analyzing
[DeepStack] Failed to call DeepStack at http://deepstack:5000/: {"success":false,"error":"invalid image"}
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at n (/home/node/app/bundle.js:9:83386)
    at h (/home/node/app/bundle.js:9:89729)
    at Module.b (/home/node/app/bundle.js:9:96406)
    at Object.<anonymous> (/home/node/app/bundle.js:581:24268)
    at /home/node/app/bundle.js:581:23561
    at Object.next (/home/node/app/bundle.js:581:23666)
    at o (/home/node/app/bundle.js:581:22380)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Viksie** [comment]
This happens with specific sample images.

Processes correctly
- Cat_20200523-074700.jpg

Errors with 
- Cat_20200523-075100.jpg
- Cat_20200523-075000.jpg

**Comment by Viksie** [comment]
Please disregard. The images were downloaded with wget.

Upon downloaded via Windows and copying to Linux, all works 100%

**Comment by danecreekphotography** [comment]
Thanks for the report, this is still a valid bug. I should be handling that exception cleanly.

**Comment by danecreekphotography** [comment]
Fixed. This will be available in the `dev` tagged image shortly, and in the `latest` tagged image on the next release.
