### ISSUE TITLE
Doesn't recognise newly added images when running on an external drive

### ISSUE THREAD

**Issue by melvinraju** [danecreekphotography/node-deepstackai-trigger#229]
Im running my setup on an external SSD (MacOS with docker) and the tool correctly reads the images that are already in the input folder and correctly returns: 

`Skipping as it was created before the service started`

but does not respond to any new images added.  No errors either, just sticks to the previous message. 

Moved the input folder to my desktop to see if it was an issue with the external drive and it runs fine

**Comment by danecreekphotography** [comment]
Hmm. Can you send me the list of environment variables listed as set on your Docker container?

**Comment by melvinraju** [comment]
<img width="826" alt="Screenshot 2020-06-18 at 19 45 24" src="https://user-images.githubusercontent.com/43336158/85059912-50648180-b19c-11ea-8172-561830190821.png">

**Comment by danecreekphotography** [comment]
It's definitely something to do with being on an external drive, I'm just not sure what. I use a 3rd party library to detect file system changes and say "hey there's a new file to look at!". The cryptic `CHOKIDAR_USEPOLLING` environment variable is specifically there to deal with issues on Docker and to some extent MacOS.

I'll have to do some reading to see if I can find someone else that's had this problem before using chokidar. It's a wildly popular library that's used all over the place so someone must have an idea.

**Comment by danecreekphotography** [comment]
What version of MacOS and Docker are you running? I'm going to have to open a bug report against the library for assistance with this one and they'll want that info. Can you also provide the logs from startup through to when the image isn't detected? Thanks!

**Comment by melvinraju** [comment]
Here you go:

**macOS:**
macOS Catalina (Version 10.15.5)

**Docker (Not sure which one you want so here's all of them):**
Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false

**Logs:**
`ai_tool_deepstack-ai_1 is up-to-date
Starting ai_tool_trigger_1 ... done
Attaching to ai_tool_deepstack-ai_1, ai_tool_trigger_1
deepstack-ai_1  | /v1/vision/detection
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/addmodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/listmodels
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/deletemodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/backup
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/restore
deepstack-ai_1  | /v1/vision/detection
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/addmodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/listmodels
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/deletemodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/backup
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/restore
deepstack-ai_1  | [GIN] 2020/06/14 - 17:39:56 | 400 |  140.617673ms |      172.22.0.3 | POST     /v1/vision/detection
deepstack-ai_1  | [GIN] 2020/06/14 - 17:40:04 | 200 |  5.903925939s |      172.22.0.3 | POST     /v1/vision/detection
deepstack-ai_1  | /v1/vision/detection
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/addmodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/listmodels
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/deletemodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/backup
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/restore
deepstack-ai_1  | /v1/vision/detection
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/addmodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/listmodels
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/deletemodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/backup
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/restore
deepstack-ai_1  | /v1/vision/detection
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/addmodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/listmodels
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/deletemodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/backup
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/restore
deepstack-ai_1  | /v1/vision/detection
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/addmodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/listmodels
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/deletemodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/backup
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/restore
deepstack-ai_1  | [GIN] 2020/06/14 - 17:52:10 | 200 |  4.984745585s |      172.22.0.3 | POST     /v1/vision/detection
deepstack-ai_1  | /v1/vision/detection
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/addmodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/listmodels
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/deletemodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/backup
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/restore
deepstack-ai_1  | [GIN] 2020/06/14 - 18:00:01 | 200 |   4.19660746s |      172.22.0.3 | POST     /v1/vision/detection
deepstack-ai_1  | /v1/vision/detection
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/addmodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/listmodels
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/deletemodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/backup
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/restore
deepstack-ai_1  | [GIN] 2020/06/14 - 18:02:09 | 200 |  4.336804113s |      172.22.0.3 | POST     /v1/vision/detection
deepstack-ai_1  | /v1/vision/detection
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/addmodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/listmodels
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/deletemodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/backup
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/restore
deepstack-ai_1  | /v1/vision/detection
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/addmodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/listmodels
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/deletemodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/backup
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/restore
deepstack-ai_1  | /v1/vision/detection
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/addmodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/listmodels
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/deletemodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/backup
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/restore
deepstack-ai_1  | /v1/vision/detection
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/addmodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/listmodels
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/deletemodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/backup
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/restore
trigger_1       | 2020-06-19T14:07:42+01:00 [Main] Starting up version 2.0.0
trigger_1       | 2020-06-19T14:07:42+01:00 [Main] Timezone offset is -60
trigger_1       | 2020-06-19T14:07:42+01:00 [Main] Current time is Fri Jun 19 2020 14:07:42 GMT+0100 (British Summer Time)
trigger_1       | 2020-06-19T14:07:42+01:00 [MQTT Manager] Unable to read the configuration file: ENOENT: no such file or directory, open '/run/secrets/mqtt'.
trigger_1       | 2020-06-19T14:07:42+01:00 [MQTT Manager] Unable to read the configuration file: ENOENT: no such file or directory, open '/config/mqtt.json'.
trigger_1       | 2020-06-19T14:07:42+01:00 [MQTT Manager] Unable to find an MQTT configuration file. If MQTT was disabled in the Docker configuration then this warning can be safely ignored. Otherwise it means something is wrong with how the container is configured. Verify the mqtt secret points to a file called mqtt.json or that the /config mount point contains a file called mqtt.json.
trigger_1       | 2020-06-19T14:07:43+01:00 [Trigger manager] Loaded configuration from /run/secrets/triggers
trigger_1       | 2020-06-19T14:07:43+01:00 [Trigger manager] Loaded configuration for Cat detector
trigger_1       | 2020-06-19T14:07:43+01:00 [Trigger manager] Loaded configuration for Dog detector
trigger_1       | 2020-06-19T14:07:43+01:00 [Telegram manager] Loaded configuration from /run/secrets/telegram
trigger_1       | 2020-06-19T14:07:43+01:00 [Trigger Cat detector] Listening for new images in /aiinput/Cat*.jpg
trigger_1       | 2020-06-19T14:07:43+01:00 [Trigger Dog detector] Listening for new images in /aiinput/Dog*.jpg
trigger_1       | 2020-06-19T14:07:43+01:00 [Main] ****************************************
trigger_1       | 2020-06-19T14:07:43+01:00 [Main] Up and running!
trigger_1       | 2020-06-19T14:07:43+01:00 [Trigger Dog detector] /aiinput/Dog_.20200614_142940203.jpg: Skipping as it was created before the service started.
trigger_1       | 2020-06-19T14:07:43+01:00 [Trigger Dog detector] /aiinput/Dog_.20200614_142935165.jpg: Skipping as it was created before the service started.
trigger_1       | 2020-06-19T14:07:43+01:00 [Trigger Dog detector] /aiinput/Dog_.20200614_142945220.jpg: Skipping as it was created before the service started.
trigger_1       | 2020-06-19T14:07:43+01:00 [Trigger Dog detector] /aiinput/Dog_2 copy 2.jpg: Skipping as it was created before the service started.
trigger_1       | 2020-06-19T14:07:43+01:00 [Trigger Dog detector] /aiinput/Dog_2 copy.jpg: Skipping as it was created before the service started.
trigger_1       | 2020-06-19T14:07:43+01:00 [Trigger Dog detector] /aiinput/Dog_2.jpg: Skipping as it was created before the service started.`


This log was taken after inputting a new image. As you can see there is no response.

**Comment by danecreekphotography** [comment]
https://github.com/paulmillr/chokidar/issues/1014

**Comment by melvinraju** [comment]
Now not able to detect any files on the desktop either. Im using the latest sample config files with this as the file path

`- /Users/MyMac/Desktop/Camera1:/aiinput`

returns this:

`Starting ai_deepstack-ai_1 ... done
Starting ai_trigger_1      ... done
Attaching to ai_deepstack-ai_1, ai_trigger_1
deepstack-ai_1  | /v1/vision/detection
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/addmodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/listmodels
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/deletemodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/backup
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/restore
trigger_1       | 2020-06-29T14:30:55+01:00 [Main] Starting up version 5.0.0
trigger_1       | 2020-06-29T14:30:55+01:00 [Main] Timezone offset is -60
trigger_1       | 2020-06-29T14:30:55+01:00 [Main] Current time is Mon Jun 29 2020 14:30:55 GMT+0100 (British Summer Time)
trigger_1       | 2020-06-29T14:30:55+01:00 [Settings] Loaded settings from /run/secrets/settings
trigger_1       | 2020-06-29T14:30:55+01:00 [MQTT] MQTT is disabled via settings.
trigger_1       | 2020-06-29T14:30:55+01:00 [Local storage] Creating local storage folders in /node-deepstackai-trigger.
trigger_1       | 2020-06-29T14:30:55+01:00 [Local storage] Enabling background purge every 60 minutes for files older than 30 minutes.
trigger_1       | 2020-06-29T14:30:55+01:00 [Local storage] Running purge
trigger_1       | 2020-06-29T14:30:55+01:00 [Triggers] Loaded configuration from /run/secrets/triggers
trigger_1       | 2020-06-29T14:30:55+01:00 [Triggers] Loaded configuration for Cat detector
trigger_1       | 2020-06-29T14:30:55+01:00 [Triggers] Loaded configuration for Dog detector
trigger_1       | 2020-06-29T14:30:55+01:00 [Pushbullet] Pushbullet is disabled via settings.
trigger_1       | 2020-06-29T14:30:55+01:00 [Pushover] Pushover is disabled via settings.
trigger_1       | 2020-06-29T14:30:55+01:00 [Telegram] Telegram is disabled via settings.
trigger_1       | 2020-06-29T14:30:55+01:00 [Trigger Cat detector] Listening for new images in /aiinput/Cat*.jpg
trigger_1       | 2020-06-29T14:30:55+01:00 [Trigger Dog detector] Listening for new images in /aiinput/Dog*.jpg
trigger_1       | 2020-06-29T14:30:55+01:00 [Main] ****************************************
trigger_1       | 2020-06-29T14:30:55+01:00 [Main] Up and running!
trigger_1       | 2020-06-29T14:30:55+01:00 [Main] Watching for changes to /run/secrets/settings
trigger_1       | 2020-06-29T14:30:55+01:00 [Main] Watching for changes to /run/secrets/triggers
trigger_1       | 2020-06-29T14:30:55+01:00 [Local storage] Purge complete
`

It does not detect the files already in the folder as it usually does and doesn't detect any newly added files either.

**Comment by melvinraju** [comment]
Note: It does detect the files when using the aiinput folder that comes in the sampleConfiguration folder

**Comment by danecreekphotography** [comment]
Sounds like your folder isn't mounted properly. Use Docker Desktop to open a terminal to the trigger container and do `ls /aiinput`. See if that returns any files.

**Comment by danecreekphotography** [comment]
I just added a bunch more logging to help make problems like this easier to sort out. Try switching your image from `danecreekphotography/node-deepstackai-trigger:latest` to `danecreekphotography/node-deepstackai-trigger:dev`. If the folder doesn't exist you'll see an error and the system won't complete startup. If it does exist it'll print out the number of images found in the folder.

**Comment by melvinraju** [comment]
A full system restart fixed the problem. The feature you've added is quite useful as I've had multiple times where I've misspelt or incorrectly entered the file path and it compiles without errors. Thanks!
