### ISSUE TITLE
Error when processing new files

### ISSUE THREAD

**Issue by r3dsouza** [danecreekphotography/node-deepstackai-trigger#236]
Hi,

Firstly, thank you for this project. It is really nice to have a docker version of the AI Tool!!

**Issue Description**
The issue I'm facing is that when new files are saved to the aiinput folder, these are correctly recognised and the analysis initiated, however, I immediately get an invalid image error. Interestingly, once an image file is already in the aiinput folder, if I simply modify the image file name, it works perfectly and gets a response from the DeepStack server and triggers web requests and MQTT. I get the same issue, no matter if images have been FTP'd by Camera, or if I manually copy files to it via samba from my laptop. I'm not sure what else to look for. Any help would be greatly appreciated!

**Log details**
2020-06-16T01:43:10+01:00 [Trigger Person detector] /aiinput/2020/06/16/Camera1_20200615_125329.0.64.jpg: Analyzing
2020-06-16T01:43:10+01:00 [DeepStack] Failed to call DeepStack at http://192.168.1.147:5000/: {"success":false,"error":"invalid image"}                                                                               
2020-06-16T01:43:10+01:00 [Trigger Person detector] /aiinput/2020/06/16/Camera1_20200615_125329.0.64.jpg: Analysis failed

**Installation details**
I'm running the latest version of the docker image in a QNAP TS-451+ NAS, following the instructions provided at [Deploying to Synology or Unraid](https://github.com/danecreekphotography/node-deepstackai-trigger/wiki/Deploying-to-Synology-and-Unraid). The aiinput folder of the container is mapped to a share in the NAS. I have Reolink 410(5MP) IP cameras, that are configured to save images to this NAS share via FTP when they detect motion. 

The DeepStackAI runs as a docker container on a separate server running  Proxmox VE. Note, I have tried using the windows AI Tool that points to the same DeepStackAI docker instance and it works perfectly!

**Docker Compose**
version: "3"

networks:
  qnet-dhcp-eth0-adadab:
    external: true
services:
  deepstackai-trigger:
    container_name: deepstackai-trigger
    image: danecreekphotography/node-deepstackai-trigger:latest
    hostname: deepstackai-trigger
    networks:
      - qnet-dhcp-eth0-adadab
    ports:
      - 4242:4242
    environment:
      - TZ=Europe/London
      - DEEPSTACK_URI=http://192.168.1.147:5000/
      - VERBOSE=true
    volumes:
      - /share/Cameras/AI_Input:/aiinput
      - /share/Volumes/DeepStackAI_Trigger/config:/config
      - /share/Volumes/DeepStackAI_Trigger/node-deepstackai-trigger:/node-deepstackai-trigger
    restart: always

**Comment by danecreekphotography** [comment]
Thanks for the detailed report! My guess is it's the combination of the network share and Docker causing the file to get read and sent to Deepstack before the file is actually fully there. Since when you rename the file is already present it works.

Can you try setting the following environment variable in your Docker config for the deepstackai-trigger container:

```none
- CHOKIDAR_USEPOLLING=false
```

My guess is it'll actually wind up being even worse and won't detect any files at all, but it's worth a try!

**Comment by danecreekphotography** [comment]
Actually scratch that. I'll have something else for you to try as soon as Docker Hub finishes building. Docker Hub is sooooo slow...

**Comment by danecreekphotography** [comment]
Ok @r3dsouza, update your docker configuration to use this image tag instead:

`danecreekphotography/node-deepstackai-trigger:issue236`

That should be the only change you need to make, leave everything else as it was when you saw the problem. Start the containers again and... hopefully... it will work!

**Comment by r3dsouza** [comment]
That did the trick! Using the docker image issue236 and adding the environment variable, it works perfectly!

Thank you!!

**Comment by danecreekphotography** [comment]
Awesome! I'll spend a bit of time testing the change then move it to the main branch. You can keep using that tag image for now and I'll let you know when it's moved to the "latest" tag so you can update your docker compose file.

**Comment by danecreekphotography** [comment]
This fix is now in the main release @r3dsouza. Please update your Docker tag to point to `latest`, thanks!

**Comment by r3dsouza** [comment]
Thanks so much! Really appreciate it.
