### ISSUE TITLE
Publish MQTT messages with the Retain flag set

### ISSUE THREAD

**Issue by r3dsouza** [danecreekphotography/node-deepstackai-trigger#249]
**Feature request**
I'd like to request that the tool publishes all MQTT messages with the retain flag set. The reason for this is that if clients subscribe to the topic after an event was triggered, they have no idea about the last published message to that topic. This also includes the `statusTopic`, so for example, clients don't know the state of the tool - if it's online or offline, if they hadn't subscribed to the topic prior to the docker container being started.

An additional consideration would be to add a boolean property to the mqtt.json file, so this ability to publish messages with the retained flag can be enabled or disabled - just in case someone does not want retained messages being published.

**Comment by danecreekphotography** [comment]
Done. Set `retain` in the `mqtt.conf` file. This will be available in the `dev` tag build in about 10 minutes. I won't push it to `latest` until I have some other stuff to release.

Thanks for the suggestion!

**Comment by r3dsouza** [comment]
Excellent! Thanks.
