### ISSUE TITLE
Support post bodies for webRequest triggers

### ISSUE THREAD

**Issue by Viksie** [danecreekphotography/node-deepstackai-trigger#276]
How should the following **_HTTP POST_** be structured for the "triggerUris" in triggers.json ?

**_Requesting URL_**
http://test:t3st1234@10.17.40.116:7001/api/executeEventAction

**_POST data_**
{
  "actionType": "CameraRecordingAction",
  "params": "AE000000-0000-0000-4321"
}

**Comment by danecreekphotography** [comment]
The system only supports GET, not POST. Try sending as a GET request instead, it will likely work:

http://test:t3st1234@10.17.40.116:7001/api/executeEventAction?actionType=CameraRecordingAction&params=AE000000-0000-0000-4321

**Comment by Viksie** [comment]
API reply:

`{"error":"3","errorString":"Method GET is not allowed for /api/executeEventAction","reply":null}`

**Comment by danecreekphotography** [comment]
Wow, Nx Witness really isn't well thought out 😂 Why aren't you using BlueIris again? 😁

**Comment by Viksie** [comment]
Runs on Linux and is $150/camera license.

**Comment by Viksie** [comment]
Hold back on this for a moment. I believe an internal event can be created on the notification to get Nx to record at a specific camera.

**Comment by Viksie** [comment]
A "Generic Event" can be created within Nx that actions a recording based on an incoming /api/createEvent event as triggered by node-deepstackai-trigger. 

This works by setting the recording option to a "Fixed duration".

The recording does not execute set to a "Pre-Recording" and "Post-Recording" option. This is being queried with Nx.
