### ISSUE TITLE
Comparing images before triggering

### ISSUE THREAD

**Issue by Viksie** [danecreekphotography/node-deepstackai-trigger#293]
False alerts are created due to identifiable objects already in view:

i.e. when monitoring a vehicle in a driveway, false alerts are generated due to:

- leaves blown around by the wind, yet with car stationary in view.

- birds moving into view, yet with a car stationary in view.

- shadows of birds flying over, yet with a car stationary in view.

- headlights of cars at night passing by, yet with a car stationary in view.

Can a comparison between two images be done, to validate the difference, i.e. a new identifiable object in view,before triggering alerts ?

**Comment by danecreekphotography** [comment]
This is what masks are for. Mask the region with the stationary car out so it won't count even if it gets detected by the AI system.

If you need to trigger on people walking through the area where the car is usually parked set up a second trigger that has no mask but doesn't have car in the list of watchObjects.

I have no interest in adding any sort of image comparison code or remembering state between sequential triggers.

**Comment by Viksie** [comment]
The problem is, the vehicle is never in the exact same spot. 

Never though of a second trigger on the same image as an option. Thanks.

May some trigger state AI memory implementation in 6 months or so. ;)
