### ISSUE TITLE
support for complex masks?

### ISSUE THREAD

**Issue by johnny2678** [danecreekphotography/node-deepstackai-trigger#298]
Great project!  I had some experience with GentlePumpkin's app a while back but had to discontinue due to long AI processing times.  Looks like a good time to revisit since BI Substream handling rolled out.

One of the things that worked well with GentlePumpkins app was his method of generating the mask from a transparent PNG file, which allows for non-standard shapes to be defined.  Not an immediate ask, just curious if there are any future plans to incorporate similar functionality?

**Comment by danecreekphotography** [comment]
Not currently, but hey, that's what feature suggestions are for. I'll noodle on it. In general anything involving image manipulation sucks to write in code 😂

**Comment by johnny2678** [comment]
ha! yea, thanks for the response.  Currently googling if there's some kind
of json coordinate PNG API mapper thing-y we can leverage :)

**Comment by johnny2678** [comment]
OpenCV might be promising? - https://stackoverflow.com/questions/61024614/convert-png-shape-into-kml-or-geojson

**Comment by danecreekphotography** [comment]
I looked at how AI Tool does it and it's pretty simplistic. I think an approach like this would be interesting: https://stackoverflow.com/questions/40952985/how-to-perform-per-pixel-collision-test-for-transparent-images. The challenge is getting access to the APIs necessary to do this. `node-canvas` is the go-to but does not run on Alpine Linux, which is the base of the Docker image currently.

I have other longstanding issues related to being on Alpine Linux that mean it's time to revisit the decision, hence the new issue #299 I opened. Switching to a different Linux flavour would open up the possibility of using `node-canvas`.

**Comment by johnny2678** [comment]
very cool... as long as it's not Windows!  😂

Thanks for considering..

**Comment by danecreekphotography** [comment]
Hey now, don't bash Windows. That's what all my machines run and what all this was written on...

**Comment by johnny2678** [comment]
yea, obviously running one myself for Blue Iris.  Not even a dev - just
prefer cmd line, docker, and Linux.  🍻

**Comment by danecreekphotography** [comment]
Windows 10 version 2004 with WSL2, Docker, and Windows Terminal is amazing. Command line, Docker, and Linux, all running like it's native on Windows. Woo!

**Comment by danecreekphotography** [comment]
I spent a bunch of time messing with this and... it's not gonna happen. Just way too much work for what I'm willing to invest, unfortunately.

**Comment by johnny2678** [comment]
no worries - didn't mean to send you down a rat hole.  thx for looking.
cheers.

**Comment by danecreekphotography** [comment]
It was fun to experiment with!
