### ISSUE TITLE
Integrating with Shinobi

### ISSUE THREAD

**Issue by r3dsouza** [danecreekphotography/node-deepstackai-trigger#300]
I would be very happy to provide some documentation for the Wiki on how to integrate this with Shinobi (another open source security camera recording project) based on my implementation. I think this may help those like me that don't use BlueIris. Let me know how I can contribute this, if it is of interest.

**Comment by danecreekphotography** [comment]
For sure! I'm always up for documentation on how to integrate with additional systems. Just write up a markdown file for "Integrating with Shinobi".

Forking the wiki to open a pull request doesn't seem to be possible so just write the file and attach it here I guess. Please run markdownlint on it before attaching. The easiest way to do that is to write the markdown file in Visual Studio Code with the markdownlint extension installed.

**Comment by r3dsouza** [comment]
Sounds good! I'll send that along in the next day or so.

**Comment by r3dsouza** [comment]
Here is the zip file with the markdown file and accompanying screenshots.
[Integration with Shinobi.zip](https://github.com/danecreekphotography/node-deepstackai-trigger/files/4828587/Integration.with.Shinobi.zip)

**Comment by danecreekphotography** [comment]
Cool, thank you! I will look at this more later this week.

**Comment by danecreekphotography** [comment]
Closing old issues.
