### ISSUE TITLE
BlueIris in Docker container

### ISSUE THREAD

**Issue by Viksie** [danecreekphotography/node-deepstackai-trigger#305]
I've got BlueIris running in a Docker container. 

Amazingly quite well.

Only current issue being timezone data not reflecting correctly. 

Would this interest you ?

**Comment by r3dsouza** [comment]
I for one would be very interested in this! I have been using Shinobi so far, mainly because I have a linux server setup and didn't want to introduce windows in my setup. Let me know if I can help with any testing or such.

**Comment by Viksie** [comment]
Fixing some minor, yet irritating issues and just need to build a new docker image and it should be good to go.

**Comment by r3dsouza** [comment]
Sounds awesome! I'm keen to give it a try :)

**Comment by danecreekphotography** [comment]
This is cool but out of scope for the documentation on this project. That would be better as a post over in ipcamtalk or a blog, since it is about installing BlueIris not this system.
