### ISSUE TITLE
Daily/weekly/monthly stats report

### ISSUE THREAD

**Issue by joshuwahaus** [danecreekphotography/node-deepstackai-trigger#306]
I think it would be great if you could enable daily/weekly/monthly reports which gives you a break down of overall and each camera to determine how effective your rules etc.

i.e. Overall: 300 alerts / 300 detections = 100% detection rate.
Camera1: 300 alerts / 150 detections = 50% detection rate

etc.

**Comment by danecreekphotography** [comment]
Thanks for the suggestion! Per-trigger statistics are now reported in the MQTT messages for each trigger. This change hasn't been promoted to the `latest` Docker tag yet but is available in the `dev` tag if you want to play with it.

Any scheduling of resetting should happen outside of the system, perhaps via automation in NodeRed, using the new REST APIs for retrieving and resetting statistics. It could also be done with a `cron` job. I will eventually add support for requesting and resetting the statistics via MQTT as well (#307).

**Comment by danecreekphotography** [comment]
Note that with #317 the location of the statistics in MQTT changed. They are now reported to `node-deepstackai-trigger/statistics/trigger`.
