### ISSUE TITLE
Too many colons when upgrading

### ISSUE THREAD

**Issue by Amishman** [danecreekphotography/node-deepstackai-trigger#326]
I am trying to upgrade from version 4.0 to 5.0. I ran the command `docker-compose pull` and it worked properly. Then I ran the command `docker-compose up` and received the following error.

![image](https://user-images.githubusercontent.com/5334426/85920904-e015ca00-b845-11ea-88d0-e21c88b9541b.png)

My docker-compose.yml:

![image](https://user-images.githubusercontent.com/5334426/85920997-9aa5cc80-b846-11ea-88d1-21cb180fd550.png)

I tried setting the path as you stated in this support request #286 but that gave me another error.

![image](https://user-images.githubusercontent.com/5334426/85921264-17d24100-b849-11ea-88ec-f48f741dc740.png)

**Log entries**

```
> 30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:22:05-04:00 [Main] ****************************************

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:22:05-04:00 [Main] Up and running!

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:22:05-04:00 [Main] Watching for changes to /run/secrets/settings

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:22:05-04:00 [Main] Watching for changes to /run/secrets/triggers

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:22:05-04:00 [Local storage] Purge complete

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:22:15-04:00 [Main] Shutting down.

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:22:15-04:00 [Trigger Cat detector] Stopped listening for new images in /AiInput/Cat*.jpg

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:22:15-04:00 [Trigger Dog detector] Stopped listening for new images in /AiInput/Dog*.jpg

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:22:15-04:00 [Trigger Person detector] Stopped listening for new images in /AiInput/Person*.jpg

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:22:15-04:00 [Trigger Car detector] Stopped listening for new images in /AiInput/Car*.jpg

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:30-04:00 [Main] Starting up version 4.0.0

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:30-04:00 [Main] Timezone offset is 240

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:30-04:00 [Main] Current time is Sat Jun 27 2020 06:26:30 GMT-0400 (Eastern Daylight Time)

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:30-04:00 [Settings] Loaded settings from /run/secrets/settings

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:30-04:00 [MQTT] MQTT is disabled via settings.

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:30-04:00 [Local storage] Creating local storage folders in /node-deepstackai-trigger.

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:30-04:00 [Local storage] Enabling background purge every 60 minutes for files older than 30 minutes.

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:30-04:00 [Local storage] Running purge

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:30-04:00 [Triggers] Loaded configuration from /run/secrets/triggers

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:30-04:00 [Triggers] Loaded configuration for Cat detector

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:30-04:00 [Triggers] Loaded configuration for Dog detector

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:30-04:00 [Triggers] Loaded configuration for Person detector

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:30-04:00 [Triggers] Loaded configuration for Car detector

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:30-04:00 [Pushbullet] No Pushbullet settings specified. Pushbullet is disabled.

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:30-04:00 [Pushover] Pushover is disabled via settings.

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:30-04:00 [Telegram] Telegram is disabled via settings.

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:30-04:00 [Trigger Cat detector] Listening for new images in /AiInput/Cat*.jpg

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:30-04:00 [Trigger Dog detector] Listening for new images in /AiInput/Dog*.jpg

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:30-04:00 [Trigger Person detector] Listening for new images in /AiInput/Person*.jpg

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:30-04:00 [Trigger Car detector] Listening for new images in /AiInput/Car*.jpg

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:30-04:00 [Main] ****************************************

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:30-04:00 [Main] Up and running!

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:30-04:00 [Main] Watching for changes to /run/secrets/settings

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:30-04:00 [Main] Watching for changes to /run/secrets/triggers

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:26:31-04:00 [Local storage] Purge complete

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:27:34-04:00 [Main] Shutting down.

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:27:34-04:00 [Trigger Cat detector] Stopped listening for new images in /AiInput/Cat*.jpg

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:27:34-04:00 [Trigger Dog detector] Stopped listening for new images in /AiInput/Dog*.jpg

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:27:34-04:00 [Trigger Person detector] Stopped listening for new images in /AiInput/Person*.jpg

30d0ff58e24d_deepstackai-blueiris_trigger_1 | 2020-06-27T06:27:34-04:00 [Trigger Car detector] Stopped listening for new images in /AiInput/Car*.jpg

30d0ff58e24d_deepstackai-blueiris_trigger_1 exited with code 0
```

**Installation details**

 - OS: Windows 10

**Comment by danecreekphotography** [comment]
This line in your `docker-compose.yml` doesn't look right:

> - o:/aiinput

You say you are upgrading from v4.0.0 to v5.0.0, but has this ever worked for you? What is the path to the images on your local machine?

**Comment by Amishman** [comment]
No, I haven't been able to get it to work yet. I just got it to update to v5.0 by changing that line to O:\AiInput. the folder is located in the root of my "O:" drive.

![image](https://user-images.githubusercontent.com/5334426/85925762-a609ef80-b868-11ea-87dc-b5682e96b4b6.png)

I must not have something set correctly because I don't see anything in the Docker log about it processing a picture. 

I also tried using GentlePumkin's AI Tool but I keep getting an error on that too.

![image](https://user-images.githubusercontent.com/5334426/85926213-d7d08580-b86b-11ea-83f0-75e4f144125b.png)

Since I use Pushbullet, I thought I would try to setup a notification to let me know. I added the sample handler with options to my trigger.json file for "Person". How do I connect this to my Pushbullet account?

![image](https://user-images.githubusercontent.com/5334426/85926102-0437d200-b86b-11ea-9630-b5ff5b2225fb.png)

**Comment by danecreekphotography** [comment]
Your volume mapping still isn't correct. please post the entire contents of your docker compose file as it currently is.

**Comment by Amishman** [comment]
I found the token for Pushbullet in the settings.json file. That should be working.

This is my docker-compose.yml
`version: "3.8"
services:
  trigger:
    volumes:
      # Change ./path_to_local_ai_images_folder to point to the folder that
      # will have the images to analyze
      - O:\AiInput

    environment:
      # Change this to match the timezone the images are produced in,
      # Typically this will be the timezone of the machine running
      # the Docker container. For a list of valid timezone values
      # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
      # The value to use is in the "TZ database name" column.
      - TZ=America/New_York

    ports:
      # This port is used by the local web server when annotated images are enabled.
      # If you change the port used by the local web server in the settings.json file
      # this also has to change to match.
      - 4242:4242

    # ------------------------------------------------------------------------
    # Don't change anything below this line unless you know what you are doing
    secrets:
      - triggers
      - settings
    image: danecreekphotography/node-deepstackai-trigger:latest
    restart: always
    depends_on:
      - deepstack-ai

  deepstack-ai:
    image: deepquestai/deepstack:latest
    restart: always
    volumes:
      - localstorage:/datastore
    environment:
      - VISION-DETECTION=True

volumes:
  localstorage:

secrets:
  settings:
    # This should point to the location of the settings.json configuration file
    file: ./settings.json
  triggers:
    # This should point to the location of the triggers.json configuration file
    file: ./triggers.json
`

**Comment by danecreekphotography** [comment]
Your volume mount isn't correct. Instead of:

> `      - O:\AiInput`

It should be:

> `      - O:/aiinput:/AiInput

Assuming your files are stored in `o:\aiinput` on your Windows machine. This is explained in detail in a comment on the sample file in github. Looks like you have a slightly older version from before I added the additional explanation:

https://github.com/danecreekphotography/node-deepstackai-trigger/blob/d56f18da1644e8c3bc6e8d56f9a3e7d4fe54dc78/sampleConfiguration/docker-compose.yml#L5-L11
