### ISSUE TITLE
No matching payload found for entity:

### ISSUE THREAD

**Issue by ne0ark** [danecreekphotography/node-deepstackai-trigger#327]
**Describe the bug**
Error log stating No Matching payload found.

2020-06-27 12:47:14 WARNING (MainThread) [homeassistant.components.mqtt.binary_sensor] No matching payload found for entity: Driveway Motion with state topic: aimotion/driveway. Payload: , with value template Template("{{value_json.baseName}}")

**Installation details**
 - OS: [e.g. Mac, Windows 10] Ubuntu 20.04
 - Docker setup [e.g. sample docker-compose.yaml, Portainer, UnRAID, etc] Docker

**Additional context**

In the version 5 I am getting that error.

**Comment by danecreekphotography** [comment]
Please provide additional information:

1. Where is this error from? HomeAssistant?
2. If it is from HomeAssistant please include your complete MQTT binary sensor configuration yaml
3. Include your complete triggers.json file

Did you have this working with prior versions of the tool?

**Comment by ne0ark** [comment]
Nm it was bug in the configuration. thnx
