### ISSUE TITLE
Email trigger

### ISSUE THREAD

**Issue by ichalmers** [danecreekphotography/node-deepstackai-trigger#328]
Awesome project.  I'd been using GentlePumpkins AI Tool, but this is great and you keep making it better.

I wondered what your thoughts were on incorporating an email trigger?

Before I saw the Hook Up's YouTube video I used to just have a python script running monitoring a folder containing the cameras snapshots, and emailing those out.  And now I've moved over to this I quite fancied continuing having email alerts.

Initially I thought I would just drive it from a MQTT message, but thought I'd check in case you had any plans to include it.

**Comment by danecreekphotography** [comment]
Thanks for the idea! No plans to add an email trigger at the moment. It would be possible, but your idea to drive via MQTT seems reasonable. I'm finding this project is really most useful as an input into an existing home automation system (I'm using Home Assistant + NodeRed) and to have the HA system do all the notifications, starting of recording, etc.
