### ISSUE TITLE
Telegram annotateImage not working

### ISSUE THREAD

**Issue by melvinraju** [danecreekphotography/node-deepstackai-trigger#332]
**Describe the bug**
`"annotateImage": true` has been set but the received image is not annotated
Here's an example:
![IMG_2755](https://user-images.githubusercontent.com/43336158/86045114-03f22f00-ba43-11ea-9fe2-4690b43b15b1.PNG)

**Log entries**

```
2020-06-29T19:50:24+01:00 [Trigger Hallway] /aiinput/YiHome_18-50-21.jpg: Analyzing

2020-06-29T19:50:24+01:00 [Trigger Hallway] /aiinput/YiHome_18-50-22.jpg: Analyzing

2020-06-29T19:50:26+01:00 [Trigger Hallway] /aiinput/YiHome_18-50-23.jpg: Analyzing

2020-06-29T19:50:29+01:00 [Trigger Hallway] /aiinput/YiHome_18-50-21.jpg: Found at least one object in the photo. (5264 ms)

2020-06-29T19:50:29+01:00 [Trigger Hallway] /aiinput/YiHome_18-50-21.jpg: Matched triggering object person

2020-06-29T19:50:29+01:00 [Trigger Hallway] /aiinput/YiHome_18-50-21.jpg: Confidence 53.64246 wasn't between threshold 60 and 100

2020-06-29T19:50:29+01:00 [Trigger Hallway] /aiinput/YiHome_18-50-21.jpg: Not triggered by person (53.64246)

2020-06-29T19:50:29+01:00 [Trigger Hallway] /aiinput/YiHome_18-50-21.jpg: Matched triggering object car

2020-06-29T19:50:29+01:00 [Trigger Hallway] /aiinput/YiHome_18-50-21.jpg: Confidence 99.797267 meets threshold 60 and 100

2020-06-29T19:50:29+01:00 [Trigger Hallway] /aiinput/YiHome_18-50-21.jpg: Triggered by car (99.797267)

2020-06-29T19:50:29+01:00 [Telegram] Sending message to -*********
```

**Installation details**
 - OS: Mac Catalina
- docker-compose.yaml version 3.8

**Comment by melvinraju** [comment]
getting this error too now, no change to the config

`trigger_1 | 2020-06-29T20:55:19+01:00 [Trigger Hallway] /aiinput/YiHome_19-29-205.jpg: Found at least one object in the photo. (387118 ms)

trigger_1 | 2020-06-29T20:55:19+01:00 [Trigger Hallway] /aiinput/YiHome_19-29-205.jpg: Matched triggering object person

trigger_1 | 2020-06-29T20:55:19+01:00 [Trigger Hallway] /aiinput/YiHome_19-29-205.jpg: Confidence 85.414416 meets threshold 60 and 100

trigger_1 | 2020-06-29T20:55:19+01:00 [Trigger Hallway] /aiinput/YiHome_19-29-205.jpg: Triggered by person (85.414416)

trigger_1 | 2020-06-29T20:55:19+01:00 [Trigger Hallway] /aiinput/YiHome_19-29-205.jpg: Matched triggering object person

trigger_1 | 2020-06-29T20:55:19+01:00 [Trigger Hallway] /aiinput/YiHome_19-29-205.jpg: Confidence 49.898523 wasn't between threshold 60 and 100

trigger_1 | 2020-06-29T20:55:19+01:00 [Trigger Hallway] /aiinput/YiHome_19-29-205.jpg: Not triggered by person (49.898523)

trigger_1 | (node:1) UnhandledPromiseRejectionWarning: Error: Unclosed tag at 105

trigger_1 | at /home/node/app/bundle.js:654:2728

trigger_1 | at g.parse (/home/node/app/bundle.js:654:3502)

trigger_1 | at g.render (/home/node/app/bundle.js:654:3574)

trigger_1 | at Object.v.render (/home/node/app/bundle.js:654:5877)

trigger_1 | at Object.t.format (/home/node/app/bundle.js:15:11909)

trigger_1 | at Object.<anonymous> (/home/node/app/bundle.js:566:65430)

trigger_1 | at /home/node/app/bundle.js:566:64052

trigger_1 | at Object.next (/home/node/app/bundle.js:566:64157)

trigger_1 | at /home/node/app/bundle.js:566:63069

trigger_1 | at new Promise (<anonymous>)

trigger_1 | at o (/home/node/app/bundle.js:566:62814)

trigger_1 | at Object.t.processTrigger (/home/node/app/bundle.js:566:64906)

trigger_1 | at e.<anonymous> (/home/node/app/bundle.js:664:12183)

trigger_1 | at /home/node/app/bundle.js:664:10205

trigger_1 | at Object.next (/home/node/app/bundle.js:664:10310)

trigger_1 | at o (/home/node/app/bundle.js:664:9024)

trigger_1 | at processTicksAndRejections (internal/process/task_queues.js:97:5)

trigger_1 | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2`

**Comment by danecreekphotography** [comment]
Weird. Please post your whole docker compose and trigger file. Thanks!

**Comment by melvinraju** [comment]
[Archive.zip](https://github.com/danecreekphotography/node-deepstackai-trigger/files/4848059/Archive.zip)

**Comment by danecreekphotography** [comment]
Thanks, will look later today. For sure that I handled promise rejection is something I should be catching.

**Comment by danecreekphotography** [comment]
Forgot: can you also include your `settings.json` file?

**Comment by danecreekphotography** [comment]
I tried annotated Telegram messages just now and it worked fine. My guess is you haven't enabled annotated image generation in your `settings.json` file by adding this:

> `enableAnnotations`: `true`

Since annotations have a performance penalty associated with them it has to explicitly be turned on. If they aren't on, even if you request it on the Telegram handler, just the unannotated image gets sent.

If you do a `docker-compose pull` to get the latest dev tagged image there's new warning messages in the logs to notify about this situation.

**Comment by melvinraju** [comment]
Cool! Got the error using the dev image. Would be good to include that in the sample config settings.json and default it to false. Thanks for the help again!

**Comment by danecreekphotography** [comment]
Good idea, done!
