### ISSUE TITLE
Home Assistant MQTT documentation error

### ISSUE THREAD

**Issue by stevearmitage** [danecreekphotography/node-deepstackai-trigger#335]
**Describe the bug**

https://github.com/danecreekphotography/node-deepstackai-trigger/wiki/Integrating-with-Home-Assistant
The documentation contains the following:

```
platform: "mqtt"
device_class: "connectivity"
name: "AI system status"
**state_topic: "node-deepstack-ai/status"**
payload_on: "online"
payload_off: "offline"
value_template: "{{value_json.state}}"
```
The state topic received is: 
**state_topic: "node-deepstackai-trigger/status"**

Suggestion: for each camera MQTT binary sensor, I have added the following to get all JSON properties as attributes:
```
  json_attributes_topic: 'node-deepstackai-trigger/status'
```

**Comment by danecreekphotography** [comment]
Oops, thanks! I fixed it. Can you show me an example of your MQTT binary sensor?

**Comment by stevearmitage** [comment]
i have a binary_sensor.yaml file
```
- platform: mqtt
  state_topic: "deepstack/driveway/motion"
  name: Camera Driveway motion AI
  device_class: motion
  payload_on: 'on'
  payload_off: 'off'
  value_template: '{{value_json.state}}'
  json_attributes_topic: 'deepstack/driveway/motion'
```

Don't have an example of the output of the camera properties.
Here are is my AI status

```
- platform: mqtt
  device_class: connectivity
  name: 'Deepstack AI status'
  state_topic: 'node-deepstackai-trigger/status'
  payload_on: 'online'
  payload_off: 'offline'
  value_template: '{{value_json.state}}'
  json_attributes_topic: 'node-deepstackai-trigger/status'
```
<img width="1000" alt="Screenshot 2020-06-30 at 21 03 12" src="https://user-images.githubusercontent.com/29444933/86129468-5439c180-bb15-11ea-9a0b-ebb7fbdbe6a4.png">

**Comment by danecreekphotography** [comment]
Perfect, thank you. Great idea! Documentation's updated.
