### ISSUE TITLE
Deepstack taking longer every time an image is added

### ISSUE THREAD

**Issue by melvinraju** [danecreekphotography/node-deepstackai-trigger#337]
**What trouble are you having?**
I am having problems with DeepStack taking longer to process every time an image is added. The longest i have observed before restarting is 2 hours! 
**Log entries**

`/v1/vision/detection

---------------------------------------

v1/vision/addmodel

---------------------------------------

v1/vision/listmodels

---------------------------------------

v1/vision/deletemodel

---------------------------------------

---------------------------------------



v1/backup

---------------------------------------

v1/restore

[GIN] 2020/07/01 - 18:11:34 | 200 | 1m35s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:12:10 | 200 | 2m6s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:12:44 | 200 | 2m38s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:13:15 | 200 | 3m7s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:13:39 | 200 | 3m30s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:14:13 | 200 | 4m3s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:14:51 | 200 | 4m36s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:15:20 | 200 | 5m8s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:15:57 | 200 | 4m42s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:16:29 | 200 | 5m5s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:17:08 | 200 | 5m28s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:17:49 | 200 | 6m6s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:18:31 | 200 | 6m46s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:19:05 | 200 | 7m16s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:19:36 | 200 | 7m48s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:19:57 | 200 | 8m5s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:20:11 | 200 | 8m16s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:20:40 | 200 | 7m46s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:21:19 | 200 | 8m36s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:21:49 | 200 | 8m32s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:22:19 | 200 | 8m59s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:22:48 | 200 | 9m32s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:23:22 | 200 | 10m0s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:23:49 | 200 | 10m25s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:24:22 | 200 | 10m55s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:24:57 | 200 | 11m32s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:25:32 | 200 | 12m1s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:26:03 | 200 | 12m34s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:26:34 | 200 | 11m40s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:27:10 | 200 | 11m55s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:27:41 | 200 | 12m4s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:28:07 | 200 | 12m28s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:28:42 | 200 | 13m0s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:29:15 | 200 | 13m31s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:29:42 | 200 | 13m56s |

172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:30:20 | 200 | 14m30s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:30:53 | 200 | 15m5s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:31:26 | 200 | 15m31s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:31:56 | 200 | 16m4s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:32:26 | 200 | 15m30s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:32:59 | 200 | 15m42s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:33:29 | 200 | 16m4s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:33:59 | 200 | 16m30s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:34:25 | 200 | 16m54s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:35:06 | 200 | 17m33s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:35:49 | 200 | 18m11s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:36:27 | 200 | 18m52s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:37:10 | 200 | 18m37s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:37:49 | 200 | 18m53s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:38:25 | 200 | 19m7s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:38:53 | 200 | 19m33s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:39:35 | 200 | 20m12s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:40:14 | 200 | 20m50s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:40:43 | 200 | 21m15s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:41:08 | 200 | 21m42s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:41:38 | 200 | 22m6s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:42:15 | 200 | 22m46s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:42:51 | 200 | 23m17s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:43:26 | 200 | 22m23s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:43:58 | 200 | 22m34s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:44:33 | 200 | 22m55s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:45:15 | 200 | 23m34s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:45:57 | 200 | 24m14s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:46:36 | 200 | 24m48s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:47:11 | 200 | 25m21s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:47:47 | 200 | 26m3s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:48:20 | 200 | 26m28s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:48:43 | 200 | 23m38s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:49:19 | 200 | 24m25s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:49:58 | 200 | 24m16s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:50:31 | 200 | 25m0s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:51:12 | 200 | 25m18s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:51:46 | 200 | 25m39s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:52:06 | 200 | 25m46s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:52:40 | 200 | 26m10s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:53:11 | 200 | 26m30s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:53:52 | 200 | 27m5s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:54:27 | 200 | 27m35s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:55:05 | 200 | 28m10s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:55:44 | 200 | 28m34s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:56:26 | 200 | 29m2s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:56:59 | 200 | 29m24s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:57:30 | 200 | 29m52s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:57:46 | 200 | 30m5s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:58:22 | 200 | 30m40s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:58:52 | 200 | 31m7s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:59:18 | 200 | 31m31s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 18:59:57 | 200 | 32m6s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:00:37 | 200 | 32m48s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:01:12 | 200 | 33m19s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:01:35 | 200 | 33m40s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:01:56 | 200 | 33m58s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:02:23 | 200 | 34m22s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:02:52 | 200 | 34m48s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:03:20 | 200 | 35m14s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:03:53 | 200 | 35m43s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:04:23 | 200 | 36m7s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:04:49 | 200 | 36m36s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:05:18 | 200 | 37m0s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:05:52 | 200 | 37m32s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:06:21 | 200 | 37m58s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:06:37 | 200 | 38m11s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:07:05 | 200 | 38m36s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:07:35 | 200 | 39m4s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:08:07 | 200 | 39m33s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:08:23 | 200 | 39m48s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:08:47 | 200 | 40m6s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:09:22 | 200 | 40m43s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:09:57 | 200 | 41m11s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:10:30 | 200 | 41m46s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:11:05 | 200 | 42m16s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:11:43 | 200 | 42m52s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:12:14 | 200 | 41m23s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:12:36 | 200 | 41m32s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:13:00 | 200 | 41m57s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:13:23 | 200 | 42m14s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:14:02 | 200 | 41m51s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:14:37 | 200 | 42m30s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:15:01 | 200 | 42m47s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:15:31 | 200 | 43m13s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:16:02 | 200 | 43m41s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:16:38 | 200 | 44m22s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:17:08 | 200 | 44m44s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:17:39 | 200 | 45m13s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:17:53 | 200 | 45m21s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:18:24 | 200 | 45m56s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:18:45 | 200 | 45m21s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:19:07 | 200 | 45m28s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:19:28 | 200 | 45m51s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:19:48 | 200 | 46m7s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:20:11 | 200 | 46m27s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:20:31 | 200 | 46m44s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:20:55 | 200 | 47m9s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:21:22 | 200 | 47m32s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:21:53 | 200 | 46m9s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:22:20 | 200 | 46m24s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:22:42 | 200 | 46m13s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:23:07 | 200 | 46m26s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:23:27 | 200 | 46m34s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:23:48 | 200 | 46m44s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:24:24 | 200 | 47m8s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:24:55 | 200 | 47m22s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:25:28 | 200 | 48m3s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:25:57 | 200 | 48m19s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:26:27 | 200 | 48m45s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:27:01 | 200 | 49m22s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:27:37 | 200 | 49m51s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:27:55 | 200 | 50m11s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:28:10 | 200 | 50m20s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:28:32 | 200 | 50m44s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:28:53 | 200 | 51m1s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:29:16 | 200 | 51m21s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:29:36 | 200 | 51m39s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:30:00 | 200 | 52m2s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:30:29 | 200 | 52m29s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:31:03 | 200 | 51m44s | 172.20.0.3 | POST /v1/vision/detection

[GIN] 2020/07/01 - 19:31:36 | 200 | 52m11s | 172.20.0.3 | POST /v1/vision/detection`

**Installation details**

 - macOS Catalina

**Comment by melvinraju** [comment]
Also now getting **a lot** of "analysis failed"
`deepstack-ai_1  | [GIN] 2020/07/01 - 20:43:52 | 400 |    7.441061ms |      172.21.0.3 | POST     /v1/vision/detection
trigger_1       | 2020-07-01T21:43:52+01:00 [Trigger Hallway] Error: Failed to call DeepStack at http://deepstack-ai:5000/: {"success":false,"error":"No valid image file found"}
trigger_1       | 2020-07-01T21:43:52+01:00 [Trigger Hallway] /aiinput/YiHome_20-43-30.jpg: Analysis failed`

**Comment by danecreekphotography** [comment]
I don't have any control over how Deepstack manages itself or its storage. On my end my containers have run for days and still process images in under a second. All I can suggest is to restart the Deepstack container and see if that helps, or delete it then do `docker-compose up` again to restart.
