### ISSUE TITLE
Analyse next image after cool down period is over

### ISSUE THREAD

**Issue by melvinraju** [danecreekphotography/node-deepstackai-trigger#338]
What I'm proposing is to only send the next **new** image (Skip the ones that occur during the cool down time) to Deepstack after the cool down period has elapsed. From what i can see from the logs the cool down time is only checked after the image has been annotated (if selected)? Correct me if I'm wrong. This change would hopefully reduce compute load, require Deepstack to only analyse necessary images and decrease turnaround times. 
A less drastic version would be to allow Deepstack to analyse the image but check cool down time before annotating . 

This lets the cool down time be truer to the the events happening on camera rather than the speed at which the program runs. What do you think?

**Comment by melvinraju** [comment]
Came across this when i had two images added into my folder with 1 second of each other. Deepstack analysed the first, annotated, sent and triggered the cool down time. The second image took deepstack 10 seconds to return which was the value of my cool down time and sent the image. Even though the two images happened within a second of each other.

**Comment by danecreekphotography** [comment]
This is already supported via the trigger-level cooldown setting (as opposed to the cooldown setting on the handler).

See https://github.com/danecreekphotography/node-deepstackai-trigger/wiki/Defining-triggers.
