### ISSUE TITLE
Annotated images placing squares at wrong place.

### ISSUE THREAD

**Issue by ne0ark** [danecreekphotography/node-deepstackai-trigger#339]
**Describe the bug**
In Blueiris I have set 4k stream as primary and secondary is set to sub stream.  Blue Iris set the this option on:

![image](https://user-images.githubusercontent.com/660607/86421277-6cd9e100-bca7-11ea-8593-533ec31cf6be.png)

**Log entries**
N/A

**Installation details**
 - OS: [e.g. Mac, Windows 10]  - Ubuntu
 - Docker setup [e.g. sample docker-compose.yaml, Portainer, UnRAID, etc] Portainer/Compose

**Additional context**
The annotated images seems to places boxes that are in wrong places. See example below:

![image](https://user-images.githubusercontent.com/660607/86421373-d35eff00-bca7-11ea-8e84-1211b375ce26.png)

The box should be on tree.

**Comment by danecreekphotography** [comment]
Interesting. I bet it's because of the "anamorphic" option. Have you tried turning "Anamorphic" off?

**Comment by ne0ark** [comment]
> Interesting. I bet it's because of the "anamorphic" option. Have you tried turning "Anamorphic" off?

If you are using both HD and sub stream it seem to auto set it.

**Comment by danecreekphotography** [comment]
Where are you seeing that BlueIris setting? I looked at my BlueIris camera configs and don't see it anywhere.

**Comment by ne0ark** [comment]
Its under camera settings --> video.

**Comment by danecreekphotography** [comment]
Thanks, I see it. I don't have it checked, and wasn't forced to check it, on any of my cameras including the ones I have running with HD + substreams. I suggest unchecking it and that should resolve the issue.
