### ISSUE TITLE
Mount point is incorrect

### ISSUE THREAD

**Issue by yangrek** [danecreekphotography/node-deepstackai-trigger#344]
I'm having following error from Docker Toolbox when running compose up:

```
$ docker-compose up
dockertoolbox_deepstack-ai_1 is up-to-date
Creating dockertoolbox_trigger_1 ... error

ERROR: for dockertoolbox_trigger_1 Cannot create container for service trigger:
invalid mount config for type "bind": invalid mount path: 'C:/Program Files/Doc
ker Toolbox/triggers.json' mount path must be absolute

ERROR: for trigger Cannot create container for service trigger: invalid mount c
onfig for type "bind": invalid mount path: 'C:/Program Files/Docker Toolbox/trig
gers.json' mount path must be absolute
ERROR: Encountered errors while bringing up the project.
```

---yaml---

```
version: "3.3"
services:
trigger:
volumes:
# Change d:/myfolder/myimages to point to the folder that will have the images
# to analyze. Only change the local path that is before the :/aiinput portion.
# Don't change the :/aiinput part. For example, if you are on Windows and your
# images are stored locally in d:/blueiris/capturedImages your final line should
# look like this:
# d:/blueIris/capturedImages:/aiinput
- d:/BlueIris/ai input:/aiinput

environment:
# Change this to match the timezone the images are produced in,
# Typically this will be the timezone of the machine running
# the Docker container. For a list of valid timezone values
# see List of tz database time zones - Wikipedia.
# The value to use is in the "TZ database name" column.
- TZ=America/Los_Angeles

ports:
# This port is used by the local web server when annotated images are enabled.
# If you change the port used by the local web server in the settings.json file
# this also has to change to match.
- 4242:4242

# ------------------------------------------------------------------------
# Don't change anything below this line unless you know what you are doing
secrets:
- triggers
- settings
image: danecreekphotography/node-deepstackai-trigger:latest
restart: always
depends_on:
- deepstack-ai

deepstack-ai:
image: deepquestai/deepstack:latest
restart: always
volumes:
- localstorage:/datastore
environment:
- VISION-DETECTION=True

volumes:
localstorage:

secrets:
settings:
# This should point to the location of the settings.json configuration file
file: ./settings.json
triggers:
# This should point to the location of the triggers.json configuration file
file: ./triggers.json

Path to image folder is (where images are stored):
D:\BlueIris\AI Input
```

**Have you tried with the sample files?**

- Yes

**Have you tried the steps in the troubleshooting guide?**

Yes

**Log entries**

See above

**Installation details**

 - OS: Win7
 - Docker setup See above

**Additional context**

-

**Comment by danecreekphotography** [comment]
My guess is Docker Toolbox doesn't support the secrets method of pointing to triggers.json and settings.json. Try using a volume mount instead:

```
version: "3.3"
services:
trigger:
volumes:
# Change d:/myfolder/myimages to point to the folder that will have the images
# to analyze. Only change the local path that is before the :/aiinput portion.
# Don't change the :/aiinput part. For example, if you are on Windows and your
# images are stored locally in d:/blueiris/capturedImages your final line should
# look like this:
# d:/blueIris/capturedImages:/aiinput
- d:/BlueIris/ai input:/aiinput
- c:/program files/docker toolbox:/config

environment:
# Change this to match the timezone the images are produced in,
# Typically this will be the timezone of the machine running
# the Docker container. For a list of valid timezone values
# see List of tz database time zones - Wikipedia.
# The value to use is in the "TZ database name" column.
- TZ=America/Los_Angeles

ports:
# This port is used by the local web server when annotated images are enabled.
# If you change the port used by the local web server in the settings.json file
# this also has to change to match.
- 4242:4242

# ------------------------------------------------------------------------
# Don't change anything below this line unless you know what you are doing
image: danecreekphotography/node-deepstackai-trigger:latest
restart: always
depends_on:
- deepstack-ai

deepstack-ai:
image: deepquestai/deepstack:latest
restart: always
volumes:
- localstorage:/datastore
environment:
- VISION-DETECTION=True

volumes:
localstorage:
```

**Comment by yangrek** [comment]
It worked!)
But the next error appeared:

$ docker-compose up
dockertoolbox_deepstack-ai_1 is up-to-date
dockertoolbox_trigger_1 is up-to-date
Attaching to dockertoolbox_deepstack-ai_1, dockertoolbox_trigger_1
deepstack-ai_1  | /v1/vision/detection
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/addmodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/listmodels
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/vision/deletemodel
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/backup
deepstack-ai_1  | ---------------------------------------
deepstack-ai_1  | v1/restore
trigger_1       | 2020-07-14T09:04:44-07:00 [Main] *****************************
***********
trigger_1       | 2020-07-14T09:04:44-07:00 [Main] Starting up version 5.1.1
trigger_1       | 2020-07-14T09:04:44-07:00 [Main] Timezone offset is 420
trigger_1       | 2020-07-14T09:04:44-07:00 [Main] Current time is Tue Jul 14 20
20 09:04:44 GMT-0700 (Pacific Daylight Time)
trigger_1       | 2020-07-14T09:04:44-07:00 [Settings] Unable to read the config
uration file: ENOENT: no such file or directory, open '/run/secrets/settings'.
trigger_1       | 2020-07-14T09:04:44-07:00 [Settings] Unable to read the config
uration file: ENOENT: no such file or directory, open '/config/settings.json'.
trigger_1       | 2020-07-14T09:04:44-07:00 [Main] Unable to find any settings f
ile.

**Comment by yangrek** [comment]
Trigger.json:


{
  "$schema": "https://raw.githubusercontent.com/danecreekphotography/node-deepstackai-trigger/main/src/schemas/triggerConfiguration.schema.json",
  "triggers": [
    {
      "name": "Car detector",
      "watchPattern": "/AI input/PARKOVKA_SD*.jpg",
      "enabled": true,
      "threshold": {
        "minimum": 10,
        "maximum": 90
      },
      "handlers": {
        "webRequest": {
          "triggerUris": ["http://localhost:81/admin?trigger&camera=Cat"]
        },
        "mqtt": {
          "topic": "aimotion/triggers/cat"
        },
        "telegram": {
          "chatIds": [1]
        }
      },
      "watchObjects": ["car"]
    },
    {
      "name": "Dog detector",
      "watchPattern": "/aiinput/Dog*.jpg",
      "enabled": true,
      "threshold": {
        "minimum": 50,
        "maximum": 100
      },
      "handlers": {
        "webRequest": {
          "triggerUris": ["http://localhost:81/admin?trigger&camera=Dog&memo={{formattedPredictions}}"]
        },
        "mqtt": {
          "messages": [{ "topic": "aimotion/triggers/dog" }]
        },
        "pushover": {
          "userKeys": ["1"]
        },
        "telegram": {
          "chatIds": [1],
          "annotateImage": true
        }
      },
      "watchObjects": ["dog"]
    }
  ]
}

**Comment by danecreekphotography** [comment]
I just guessed at this line based on your prior screenshots:

`- c:/program files/docker toolbox:/config`

Given the error:

`ENOENT: no such file or directory, open '/config/settings.json'`

the path I used for the volume mapping isn't correct. You should modify the volume mapping to point to the actual folder where your settings.json and triggers.json file is located.

I highly recommend you create a dedicated folder that is *not* inside Program Files for this. Make a folder somewhere in your My Documents folder or elsewhere on your c: drive to store these files, then set the point point to that location.

**Comment by yangrek** [comment]
Well, but this path is right actually...hmm
c:/program files/docker toolbox
Okey, should I move everything from the old folder or only these 3 yml and json files?

**Comment by danecreekphotography** [comment]
Just the yaml file and two json files. It's possible that because the folder is program files there are administrator protections in place that prevent it from being mounted properly.

**Comment by yangrek** [comment]
Well, still same error(((
New folder is C:/DeepQuest
![image](https://user-images.githubusercontent.com/68291333/87451254-50736800-c608-11ea-9765-93c293198216.png)

**Comment by danecreekphotography** [comment]
Are you positive you ran `docker-compose up` inside your new c:\DeepQuest folder, and that the `docker-compose.yaml` file inside that folder is the one you made the edits to?

Unfortunately I'm out of ideas for what to suggest. I just tried this locally and what I gave you works and loads correctly using Docker Desktop. The fundamental issue you are facing is the config files are not getting mounted into Docker correctly. Until you can figure out why Docker Toolbox/Docker on your computer can't mount the config files nothing will work.

**Comment by yangrek** [comment]
Well, you were right, running compose up from another place helped)
But again:

$ docker-compose up
deepquest_deepstack-ai_1 is up-to-date
Starting deepquest_trigger_1 ... error

ERROR: for deepquest_trigger_1  Cannot start service trigger: driver failed prog                                              ramming external connectivity on endpoint deepquest_trigger_1 (1d61f9554e06758d2                                              cff3e236ff0e239eb021af84f11d386ecda3da09581b362): Bind for 0.0.0.0:4242 failed:                                               port is already allocated

ERROR: for trigger  Cannot start service trigger: driver failed programming exte                                              rnal connectivity on endpoint deepquest_trigger_1 (1d61f9554e06758d2cff3e236ff0e                                              239eb021af84f11d386ecda3da09581b362): Bind for 0.0.0.0:4242 failed: port is alre                                              ady allocated
Encountered errors while bringing up the project.

**Comment by danecreekphotography** [comment]
That means you have an existing instance of the service running. I don't know how Docker Toolbox can show you running instances but you need to find them and stop them. If you were using Docker Desktop you could bring up the UI and kill off the existing running containers.

**Comment by yangrek** [comment]
Decided to wait for some implementation of this AI into user-friendly commercial products) I lack IT knowledge to get things working now) Anyway, great thanks for support)
