### ISSUE TITLE
Document how to get node-deepstackai-trigger working on Unraid

### ISSUE THREAD

**Issue by MattW2** [danecreekphotography/node-deepstackai-trigger#349]
This tutorial assumes that you will be running _deepstack_ and _node-deepstackai-trigger_ as docker containers on an Unraid server.

Hope this helps people trying to get this running on Docker. I have had it working for the last week and it has been working smoothly while using far less system resources than trying to run deepstack on a Windows VM. I would be happy to turn this into a Wiki page with screen shots on the node-deepstackai-trigger git repository. 

 ### Setup deepstack as a docker container
Since deepstack isn't in the Unraid app store we will need to manually setup the container. Create a new container with the following parameters
- **Name:** deepstack
- **Repository:** deepquestai/deepstack:latest
- **Network Type:** Custom :br0
It is important to use this and not Host or Bridge as Unraid will prevent docker containers from talking to each other if they are connected using Host or Bridge
- **Fixed IP address (optional):** Assign an unused IP on your network
- **Console shell command:** Shell
- **Privileged:** Off
#### Variable 1
- **Name:**  Key 1
- **Key:** PUID
- **Value:** 1000
#### Variable 2
- **Name:**  Key 2
- **Key:** PGID
- **Value:** 1000
#### Variable 3
- **Name:**  VISION-DETECTION
- **Key:** VISION-DETECTION
- **Value:** True
#### Path 1
- **Name:**  Datastore
- **Container Path:** /datastore
- **Host Path::** /mnt/user/appdata/deepstack/datastore/
This is just where I use, you can use any location
- **Access Mode:** Read/Write
#### Port 1
- **Name:**  Web
- **Host Port:** 5000
- **Connection Type:** TCP
- **Description:** Container Port: 5000

Click done, wait for deepstack to download and run, it can take 20 minutes or more. Check that it is running by going to http://fixedIPYouAssigned:5000

 ### Setup node-deepstackai-trigger as a docker container
Since node-deepstackai-trigger isn't in the Unraid app store we will need to manually setup the container. Create a new container with the following parameters
- **Name:** node-deepstackai-trigger
- **Repository:** danecreekphotography/node-deepstackai-trigger:latest
- **Network Type:** Custom :br0
It is important to use this and not Host or Bridge as Unraid will prevent docker containers from talking to each other if they are connected using Host or Bridge
- **Fixed IP address (optional):** Assign an unused IP on your network
- **Console shell command:** Shell
- **Privileged:** Off
#### Variable 1
- **Name:**  Images
- **Key:** PUID
- **Value:** 1000
#### Variable 2
- **Name:**  Images
- **Key:** PGID
- **Value:** 1000
#### Variable 3
- **Name:**  Time Zone
- **Key:** TZ
- **Value:** Enter Timezone such as **America/New_York**
#### Variable 4
- **Name:**  VERBOSE
- **Key:** VERBOSE
- **Value:** true
#### Path 1
- **Name:**  Images
- **Container Path:** /aiinput
- **Host Path::** /mnt/user/Blue Iris/deepstackai_images/
This is where your Blue Iris images will be stored. It is important that however you run Blue Iris that it has write access to this folder. In my case I run Blue Iris on a Windows VM and have this folder available to docker and the Windows VM
#### Path 2
- **Name:**  Config
- **Container Path:** /config
- **Host Path::** /mnt/user/appdata/node-deepstackai-trigger/config/
This is where you will put your versions of the example files in [Example settings.json and triggers.json](https://github.com/danecreekphotography/node-deepstackai-trigger/tree/main/sampleConfiguration)
- **Access Mode:** Read/Write
#### Port 1
- **Name:**  Host Port 1
- **Host Port:** 4242
- **Connection Type:** TCP
- **Description:** Container Port: 4242

![deepstack Unraid Docker](https://user-images.githubusercontent.com/12071816/87895560-c5cda700-ca13-11ea-9159-cf3fec2ff970.jpg)
![node-deepstackai-trigger Unraid Docker](https://user-images.githubusercontent.com/12071816/87895562-c5cda700-ca13-11ea-9eec-17bf00dfbb4e.jpg)

**Comment by danecreekphotography** [comment]
Very nice! Yes, I'd love to have this as proper documentation for the wiki. If you stick it in a markdown file and make sure it passes markdownlint I'd be happy to include it. I think you can attach it all as a zip file here?

One thing I've also wanted to do is actually get this listed in the UnRaid app store but have never had any luck finding documentation on how to do that. Do you by any chance know the submission process?

**Comment by the-speedmax** [comment]
Tks for this nice "Howto".
The only think that I modify was the Network Type.
I was not able to figure how to change the Subnet of a Docker Network.
So I used the Bridge. I forwarded port 4242 to 4241 and the 5000 to 83.
It work!

![image](https://user-images.githubusercontent.com/613242/88093236-b9eefb80-cb5f-11ea-88d8-4d43ae1e5dc7.png)

![image](https://user-images.githubusercontent.com/613242/88093565-2ec23580-cb60-11ea-8317-1d7c254ffe8a.png)

Tks again!

**Comment by MattW2** [comment]
> Very nice! Yes, I'd love to have this as proper documentation for the wiki. If you stick it in a markdown file and make sure it passes markdownlint I'd be happy to include it. I think you can attach it all as a zip file here?
> 
> One thing I've also wanted to do is actually get this listed in the UnRaid app store but have never had any luck finding documentation on how to do that. Do you by any chance know the submission process?

I haven't tried to submit an application myself to the UnRaid app store but this is the best post I've found so far that points to how to do it
https://forums.unraid.net/topic/55503-how-to-submit-new-docker-containers-to-community-apps/
and
https://forums.unraid.net/topic/57181-docker-faq/#comment-566084

**Comment by mattiapsu** [comment]
Great documentation, and I believe I've followed exactly. I've used the bridge version and forwarded ports, which I prefer. I've even tried using the custom Network type. Unfortunately, it doesn't look like the trigger is pulling the images. The watch pattern is correct, and I've moved my aiinput folder to a number of places including the config folder.

This is all the log ever says. I assume 'unable to read' the secrets is a check before just picking up the setting.json in config, but maybe I am actually missing something. Not using secrets right now.

2020-11-05T23:30:17-05:00 [Main] ****************************************
2020-11-05T23:30:17-05:00 [Main] Starting up version 5.4.0

2020-11-05T23:30:17-05:00 [Main] Timezone offset is 300
2020-11-05T23:30:17-05:00 [Main] Current time is Thu Nov 05 2020 23:30:17 GMT-0500 (Eastern Standard Time)
2020-11-05T23:30:17-05:00 [Settings] Unable to read the configuration file: ENOENT: no such file or directory, open '/run/secrets/settings'.
2020-11-05T23:30:17-05:00 [Settings] Loaded settings from /config/settings.json

**Comment by danecreekphotography** [comment]
@mattiapsu please open a new github issue for your specific troubleshooting request. Make sure to include the entire output log as well as your settings.json and triggers.json file.

**Comment by danecreekphotography** [comment]
Closing old issues.
