### ISSUE TITLE
Retrieve image for MQTT when annotations are disabled

### ISSUE THREAD

**Issue by melvinraju** [danecreekphotography/node-deepstackai-trigger#350]
I'm trying to send the detected image to a google home hub over MQTT/Node-Red but found that they can only be accessed if annotations are turned on? Can there be a separate web server for which non-annotated trigger images are sent?

**Comment by danecreekphotography** [comment]
Set `enableWebServer` to `true` in `settings.json` (see https://github.com/danecreekphotography/node-deepstackai-trigger/wiki/Configuration#system-configuration).

Then the original images are available at `http://machineaddress/snapshots/originalfilename.jpg`.

**Comment by melvinraju** [comment]
Thanks!

**Comment by danecreekphotography** [comment]
Small correction: they're accessible at http://machineaddress:4242

**Comment by melvinraju** [comment]
Having problems accessing this.

Using:
http://localhost:4242/FD_13-14-49_copy_8.jpg   - Returns the annotated image
http://localhost:4242/annotations/FD_13-14-49_copy_8.jpg   -Returns the annotated image
http://localhost:4242/snapshots/FD_13-14-49_copy_8.jpg    -Returns Cannot GET /snapshots/FD_13-14-49_copy_8.jpg

**Comment by danecreekphotography** [comment]
Mmmm, yeah. Looks like there's a bug. I'll get one open and fix it tonight.

**Comment by danecreekphotography** [comment]
https://github.com/danecreekphotography/node-deepstackai-trigger/issues/351

**Comment by danecreekphotography** [comment]
Sooooooooooooooooooooo it's not really a bug. It's an "oh you dummy you never actually implemented that" 😂 Will close the bug and use this to track since it's an actual feature enhancement at this point.

**Comment by danecreekphotography** [comment]
This is ready for you to try @melvinraju. Use `danecreekphotography/node-deepstackai-trigger:issue350` for the Docker image and `http://localhost:4242/originals/FD_13-14-49_copy_8.jpg` for the image. Let me know if it works.

**Comment by melvinraju** [comment]
This is working perfectly 🚀 Am I right in thinking these images are removed with the routine purge?

**Comment by danecreekphotography** [comment]
Yep. You can control how often the purge runs and how old an image has to be before it is removed with the settings.json file. https://github.com/danecreekphotography/node-deepstackai-trigger/wiki/Configuration#system-configuration

**Comment by danecreekphotography** [comment]
This is now released, you can switch back to using the `latest` image tag.

**Comment by melvinraju** [comment]
hey @danecreekphotography can you check if this is working for you? i havent used it in a while and have tried recently and am getting a Cannot GET error again when using http://localhost:4242/originals/FD_1.jpg

**Comment by danecreekphotography** [comment]
Mmm, weird. I'm getting a GET error too. I'll look later today!

**Comment by danecreekphotography** [comment]
So I'm not entirely sure what's going on but can you try restarting the container and see if that makes future images show up? It's working for me now.

If you have the problem again try opening a terminal to the container using Docker and do `ls /node-deepstackai-trigger/originals` to see if the images are there.

**Comment by melvinraju** [comment]
Tried restarting the container and error persists. 
When I do just `ls /node-deepstackai-trigger` it comes up with two folders `annotations` and `snapshots` no originals folder.

**Comment by melvinraju** [comment]
Just did a docker-compose pull and has now updated to have the originals folder. I can see the images now!
