### ISSUE TITLE
How to send msg.payload.example in triggers file

### ISSUE THREAD

**Issue by melvinraju** [danecreekphotography/node-deepstackai-trigger#365]
Hey,
I'm trying to send the baseName of the image as a separate payload and was wondering what the notation for this would be?
here's what i have currently have which returns "hey there's someone at the door" in the msg.payload 
`          "messages": [
            {
            "topic": "doorbell", 
            "payload": "hey, someone's at the door",
            "offDelay": 0
            },`

How would I add msg.payload.file: {{baseName}} to the MQTT message?

**Comment by danecreekphotography** [comment]
Unfortunately you can only set the payload to a string, not a full JSON object, so there isn't a way to get `msg.payload.file`. I suggest using the default payload and then constructing the string you want at the receiving end.
