### ISSUE TITLE
Unable to reach deepstack image in Docker

### ISSUE THREAD

**Issue by TrunkMonk** [danecreekphotography/node-deepstackai-trigger#367]
**What trouble are you having?**

I have configured BlueIris and the triggers are all working and the Deepstack ai instance is running in Docker, but is unreachable from AITool.  It looks like the image is running correctly and waiting,but logs in AiTool report that the deepstack server is unreachable.  

**Have you tried with the sample files?**

- Yes, copied the content from the sample files to my local computer where docker is running

**Have you tried the steps in the troubleshooting guide?**

https://github.com/danecreekphotography/node-deepstackai-trigger/wiki/Troubleshooting

- Yes, my CPU supports AVX, watch patterns are correct and CPU peformance isn't currently ans issue

**Log entries**

**Installation details**

 - OS: Windows 10 Enterprise build 18363 
 - Docker setup - Local Docker install using quick start steps, increased docker resources to 4 GB, 2 cpus, swap 1GB

**Additional context**
[docker_trigger.txt](https://github.com/danecreekphotography/node-deepstackai-trigger/files/5087149/docker_trigger.txt)
[docker_deepstack-ai.txt](https://github.com/danecreekphotography/node-deepstackai-trigger/files/5087150/docker_deepstack-ai.txt)

I suspect I misconfigured something as I don't know how to determine what the IP of the Deepstack instance in Docker is 

AiTool log:

[17.08.2020, 15:27:15.550]: Starting analysis of N:\AI_Input\GateFrontSD.20200817_152713945.jpg
[17.08.2020, 15:27:15.555]: (1/6) Uploading image to DeepQuestAI Server
[17.08.2020, 15:27:19.563]: System.Net.Http.HttpRequestException | An error occurred while sending the request. (code: -2146233079 )
[17.08.2020, 15:27:19.568]: ERROR: Processing the following image 'N:\AI_Input\GateFrontSD.20200817_152713945.jpg' failed. Can't reach DeepQuestAI Server at http://localhost:5000/v1/vision/detection.

**Comment by danecreekphotography** [comment]
You shouldn't be using AI Tool at all. AI Tool is a separate app and is not needed or used by this solution. Your docker_trigger.txt log file shows that everything is up and running and working correctly.

**Comment by TrunkMonk** [comment]
Ohhh... I guess I've misunderstood the function of this docker image.  I thought it was an alternative to the windows install of deepstack.  

I've now stopped the AiTool service I created previously  and walked around in front of the cameras but am not getting any alerts or captures of me in any any frame in BI, How do I know if deepstack has processed any people or car detections

**Comment by danecreekphotography** [comment]
Check your logs for the trigger container in Docker Desktop. There will be tons of logs showing you what's happening.
