### ISSUE TITLE
Detection and therefor triggering stops working

### ISSUE THREAD

**Issue by tripp396** [danecreekphotography/node-deepstackai-trigger#370]
After a couple hours it seems to not be detecting new photos in the input directory. The cameras are putting the photos there, the container just stops seeing them. 

Are there some logs that would be the best to look at? It works for the first couple hours after restart and then just stops seeing new photos.

**Comment by danecreekphotography** [comment]
There are copious logs available in Docker Desktop. Look for the logs on the _trigger_ container and you'll see if it is still detecting images.

My guess is this is related to having too many images in the detection folder. See the 80% CPU troubleshooting instructions on the wiki and try the changes suggested there: https://github.com/danecreekphotography/node-deepstackai-trigger/wiki/Troubleshooting#problem-the-container-causes-80-cpu-usage.

**Comment by tripp396** [comment]
Found out the issue. Seems my watchtower installation was trying to stop the containers unsuccesfully when trying to update all my containers. Disabled watchtower and have had no issues since.
