### ISSUE TITLE
Is it possible to use a tensorflow model I found with this docker?

### ISSUE THREAD

**Issue by Unthred** [danecreekphotography/node-deepstackai-trigger#372]
**What trouble are you having?**

I would like to use a tensorflow model with this docker as it will detect more objects, specifically Squirrels. Is this possible?

**Installation details**

- Docker using docker-compose.yaml on UnRAID

**Comment by danecreekphotography** [comment]
The only tested AI system is Deepstack. If Tensorflow has the same API format to call, and same response value as Deepstack it should work. If there's any differences however it wouldn't.
