### ISSUE TITLE
Masking by using image mask instead of many rectangles

### ISSUE THREAD

**Issue by juched78** [danecreekphotography/node-deepstackai-trigger#373]
When your camera shot has a curve or more intricate item to mask out, it is hard to do with many small rectangles.  

Other solutions have allowed for a masked image to be used, as an overlay, and ignore when it overlaps.

Not sure if there is a TS module to help with this, so perhaps this is not an easy task.

**Comment by neileadobe** [comment]
This was previously requested and investigated here: https://github.com/danecreekphotography/node-deepstackai-trigger/issues/298. Unfortunately it's just not something that's feasible.

**Comment by danecreekphotography** [comment]
This was previously requested and investigated: https://github.com/danecreekphotography/node-deepstackai-trigger/issues/298. Unfortunately it's not feasible.
