### ISSUE TITLE
One json example in docs has a syntax error

### ISSUE THREAD

**Issue by TonyBrobston** [danecreekphotography/node-deepstackai-trigger#374]
If you search for `"retain: true` here: 
https://github.com/danecreekphotography/node-deepstackai-trigger/wiki/Configuration#

`"retain: true` should be `"retain": true`

I don't know how to update this, so I'm dropping the information here.

Hope this helps 👍 .

**Comment by danecreekphotography** [comment]
Oops! Thanks, will fix later today.

**Comment by danecreekphotography** [comment]
Fixed!
