### ISSUE TITLE
Issues with Docker on Windows Server 2019

### ISSUE THREAD

**Issue by peterbeeston** [danecreekphotography/node-deepstackai-trigger#375]

**Comment by peterbeeston** [comment]
> A clear and concise description of what you're stuck on.

Error raised when running docker-compose up:

**docker-compose.yaml**:
version: "3.8"
services:
  trigger:
    volumes:
      # Change d:/myfolder/myimages to point to the folder that will have the images
      # to analyze. Only change the local path that is before the :/aiinput portion.
      # Don't change the :/aiinput part. For example, if you are on Windows and your
      # images are stored locally in d:/blueiris/capturedImages your final line should
      # look like this:
      # d:/blueIris/capturedImages:/aiinput
      - D:/BlueIris/capturedImages:/aiinput

    environment:
      # Change this to match the timezone the images are produced in,
      # Typically this will be the timezone of the machine running
      # the Docker container. For a list of valid timezone values
      # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
      # The value to use is in the "TZ database name" column.
      - TZ=Europe/London

    ports:
      # This port is used by the local web server when annotated images are enabled.
      # If you change the port used by the local web server in the settings.json file
      # this also has to change to match.
      - 4242:4242

    # ------------------------------------------------------------------------
    # Don't change anything below this line unless you know what you are doing
    secrets:
      - triggers
      - settings
    image: danecreekphotography/node-deepstackai-trigger:latest
    restart: always
    depends_on:
      - deepstack-ai

  deepstack-ai:
    image: deepquestai/deepstack:latest
    restart: always
    volumes:
      - localstorage:/datastore
    environment:
      - VISION-DETECTION=True

volumes:
  localstorage:

secrets:
  settings:
    # This should point to the location of the settings.json configuration file
    file: ./settings.json
  triggers:
    # This should point to the location of the triggers.json configuration file
    file: ./triggers.json

**settings.json**
{
  // Leave this line alone. It enables Intellisense when editing this file in Visual Studio Code.
  "$schema": "https://raw.githubusercontent.com/danecreekphotography/node-deepstackai-trigger/main/src/schemas/settings.schema.json",

  // This is the default uri for Deepstack when deploying using the docker-compose.yaml file
  // provided in this sampleConfiguration folder. If you have another deployment of Deepstack
  // running elsewhere change this setting to point to the correction location.
  "deepstackUri": "http://deepstack-ai:5000/",

  // Set this to true to enable annotated images for use in trigger handlers.
  // There is a performance penalty to using this, leave it off unless
  // you really want to see the annotated images.
  "enableAnnotations": false,

  // Set this to true to enable the internal web server for remote access
  // to processed and annotated images.
  "enableWebServer": false,

  // Enables verbose logging. Useful when setting up the system to ensure
  // everything is running correctly.
  "verbose": true,

  // Set this to true if your images are stored in a remote folder that's
  // mounted as a network share and then mapped to the Docker image.
  "awaitWriteFinish": false,

  // Provides the configuration details for your MQTT server. To enable
  // mqtt set the uri, username (if required), password (if required),
  // and set enabled to true.
  "mqtt": {
    "uri": "mqtt://xxxxxxxxxxx:1883",
    "username": "xxxxxxxxxxxxxxx",
    "password": "xxxxxxxxxxxxxxx",
    "enabled": true,
    "retain": true
  },

  // Provides the configuration details for Telegram bot messages.
  // Set the botToken and enabled to true to use Telegram.
  "telegram": {
    "botToken": "insert bot token here",
    "enabled": false
  },

  // Provides the configuration details for Pushbullet notifications.
  // Set the accessToken and enabled to true to use Pushbullet.
  "pushbullet": {
    "accessToken": "access token here",
    "enabled": false
  },

  // Provides the configuration details for Pushover notifications.
  // Set the apiKey, userKey, and enabled to true to use Pushover.
  "pushover": {
    "apiKey": "api key here",
    "userKey": "user key here",
    "enabled": false
  }
}

**triggers.json**
{
  "$schema": "https://raw.githubusercontent.com/danecreekphotography/node-deepstackai-trigger/main/src/schemas/triggerConfiguration.schema.json",
  "triggers": [
    {
      "name": "Dog detector",
      "watchPattern": "/BlueIris/capturedImages/Dog*.jpg",
      "enabled": false,
      "threshold": {
        "minimum": 50,
        "maximum": 100
      },
      "handlers": {
        "webRequest": {
          "triggerUris": ["http://localhost:81/admin?trigger&camera=Dog&memo={{formattedPredictions}}"]
        },
        "mqtt": {
          "messages": [{ "topic": "aimotion/triggers/dog" }]
        },
        "pushover": {
          "userKeys": ["1"]
        },
        "telegram": {
          "chatIds": [1],
          "annotateImage": true
        }
      },
      "watchObjects": ["dog"]
    },
    {
      "name": "Office detector",
      "watchPattern": "/BlueIris/capturedImages/office*.jpg",
      "enabled": true,
      "threshold": {
        "minimum": 50,
        "maximum": 100
      },
      "handlers": {
        "mqtt": {
          "messages": [{"topic": "aimotion/trigger/office"}]
        }
      },
      "watchObjects": ["person","bicycle","car","dog","motorcycle","truck"]
    }
  ]
}

Have portainer installed which shows that the "nodedeepstackaitrigger_deepstack-ai_1" container has been created and is running.

OS: Windows 2019 Server Standard.
Docker EE which is part of Windows 2019.
Docker version 19.03.11, build 0da829ac52
docker-compose version 1.27.3, build 4092ae5d

**Comment by peterbeeston** [comment]
Closed in error

**Comment by danecreekphotography** [comment]
Does D:/BlueIris/capturedImages exist on your computer? The error says it doesn't.

**Comment by peterbeeston** [comment]
Hi,
Yes that folder does exist, and I have double checked it.

I copied the path from the File Explorer address bar and pasted it into the file.

Peter.

**Comment by danecreekphotography** [comment]
Are you running this in Portainer? Or just straight from a Windows command line using `docker-compose`?

Is Windows running natively on the machine? Or is Windows in a virtual machine?

**Comment by peterbeeston** [comment]
Hi,
The machine is running native Windows 2019 Server Standard, with the built-in Docker-EE engine.
This was run in a Power Shell (Admin) session.
I have installed other docker containers this way and have had no issues, as is shown in that the DeepStackAI container is running.
Docker is also running Portainer and Portainer-Agent.

Thanks for the quick reply.

Peter.

**Comment by danecreekphotography** [comment]
Is the folder local to the machine or is it a mounted shared drive?

**Comment by danecreekphotography** [comment]
What happens if you do a `dir D:\BlueIris\capturedImages` from PowerShell?

**Comment by peterbeeston** [comment]
Hi,
The drive is a local disk and the dir command returns:
PS C:\Windows\system32> dir D:\BlueIris\capturedImages


    Directory: D:\BlueIris\capturedImages


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       21/09/2020     14:32              0 Test.txt

This file is just there so that there is something to return.

Peter.

**Comment by danecreekphotography** [comment]
Unfortunately I'm out of ideas :( This is purely a Docker issue and nothing to do with any of the stuff I wrote. Perhaps you can try asking on StackOverflow, although all of the threads on this error I saw there were related to things you say are not applicable in your case.

**Comment by peterbeeston** [comment]
Hi,
I agree, I think that this is a 2019 specific issue, but was hoping that you may have heard something.

I have an inkling that it may be a PS/Docker-Compose/Windows folders issue, so I an going to try the CMD prompt instead on PS. If I find anything I will let you know.

Peter.

**Comment by danecreekphotography** [comment]
Other things to try:

1. A different folder name entirely
2. Install Docker Desktop (sounds like you are using something else built in to Windows server?)
