### ISSUE TITLE
Web interface is not working

### ISSUE THREAD

**Issue by Acetyld** [danecreekphotography/node-deepstackai-trigger#376]
**Describe the bug**
Web interface is not working
![afbeelding](https://user-images.githubusercontent.com/55088242/94373838-51487000-0108-11eb-8c07-98b3fc031e2f.png)

**Log entries**
`Cannot GET /`

**Installation details**
 - OS: Win 10
 - Docker setup Docker Compose

**Additional context**
No clue why but webinterface is not working also nto with localhost:4242

**Comment by danecreekphotography** [comment]
Have you enabled annotations? If not there's nothing available at the `/` endpoint. There are a few URLs that will get you folders of images if you go directly to the right path:

* REST API for triggering things: https://github.com/danecreekphotography/node-deepstackai-trigger/wiki/REST-API
* Viewing annotated images (if you have it enabled): http://localhost:4242/annotations or http://localhost:4242/
* Viewing original images: http://localhost:4242/originals
