### ISSUE TITLE
Vehicular identification & recognition

### ISSUE THREAD

**Issue by gostlund** [danecreekphotography/node-deepstackai-trigger#379]
**Is your feature request related to a problem? Please describe.**
It is unrelated to a specific problem, I just would like to get more information provided in the triggers, to expand possible reactions to events.

**Describe the solution you'd like**
I'm looking to have additional information being supplied in the triggers, like, make & model of the vehicle, or being able to recognize if it's an emergency services vehicle, or delivery truck (UPS/FedEx/Purolator/DHL/etc...)

**Describe alternatives you've considered**
I haven't actually looked at other alternatives, as I wasn't able to find anything else that does this, I just felt that this project might be a good foundation to try and build upon to the featureset of the AI here

**Additional context**
Feature Request, it's not broken, but we can still fix it, right?

**Comment by danecreekphotography** [comment]
Unfortunately the only info available is what Deepstack provides. You can see what they have available at https://nodejs.deepstack.cc/object-detection, scroll down to "Classes". It's just general object classes and nothing more.

This project just interfaces with Deepstack and doesn't do any AI processing of its own.
