### ISSUE TITLE
Disable purge interval

### ISSUE THREAD

**Issue by ghzgod** [danecreekphotography/node-deepstackai-trigger#399]
Could we set this to 0 and have it disable completely?  I like to keep my data indefinitely if possible.  I appreciate it in advance if this is at all possible/easy to implement.

**Comment by danecreekphotography** [comment]
This is ready for you to try out. Change your Docker tag from `latest` to `issue399`, then set `purgeInterval` to `0` in your `settings.json` file. Let me know how it works out.

**Comment by danecreekphotography** [comment]
Oops, git malfunction. Hang tight, changes aren't in that build yet.

**Comment by danecreekphotography** [comment]
Ok this is really ready :) Give it a try!

**Comment by ghzgod** [comment]
> Ok this is really ready :) Give it a try!

Wow, that was a super quick turn around. This seems to be working a-ok!!!!  Thank you for considering my request and further for deploying it!  I was doing all of this in a single node red flow but this is much easier.

**Comment by danecreekphotography** [comment]
Thanks for verifying! This will be available in the `latest` tagged image in about 30 minutes.
