### ISSUE TITLE
Easily identify which images are being detected and eliminated by renaming the files

### ISSUE THREAD

**Issue by LavaTiger99** [danecreekphotography/node-deepstackai-trigger#409]
One option to quickly see if your tolerances are working as expected, is to have the camera images renamed after passing through deepstack, changing the file name to what was detected in that frame ("false-positive-2020-12-01-1862.jpg", "dog-person-truck-2020-12-01-1862.jpg"). That way one can quickly browse the images watch folder and see how well it is working, rather than comparing logs to filenames.

**Comment by danecreekphotography** [comment]
Thanks for the suggestion! One of my design guidelines for this system is that it only touches/modifies things it created. Since those files were created outside of the system (by BlueIris or some other service) I won't be adding anything that changes the filenames.
