### ISSUE TITLE
Glob pattern in trigger.watchPattern doesn't work...

### ISSUE THREAD

**Issue by salcio** [danecreekphotography/node-deepstackai-trigger#412]
**Describe the bug**
When trying to use a glob pattern like '/aiinput/**/Dog*.jpg' in trigger.watchPattern exeption in verifyTriggerWatchLocation method is raised ( Unable to read contents of watch folder ${trigger.watchPattern} for trigger ${trigger.name}. Check and make sure the image folder is mounted properly. ${e})

**Log entries**
Unable to read contents of watch folder ${trigger.watchPattern} for trigger ${trigger.name}. Check and make sure the image folder is mounted properly. ${e}

**Installation details**
 - OS: Unraid
 - Docker setup UnRAID

**Additional context**

**Comment by danecreekphotography** [comment]
Ahhhh good catch, fascinating. Totally forgot that glob patterns are a thing when I added that check because of the number of people specifying incorrect folder locations.

**Comment by danecreekphotography** [comment]
I finally remembered this 😂 My bad! This is merged. Would you mind changing to the `dev` image in your docker config and confirming it works?

**Comment by salcio** [comment]
I'm not able to change that easily on my environment as I'm using image with my changes for archiving. but my image contains the changes from this issue and it works.

**Comment by danecreekphotography** [comment]
Ok thanks!
________________________________
