### ISSUE TITLE
Set lint to fail the build on some warnings. 

### ISSUE THREAD

**Issue by salcio** [danecreekphotography/node-deepstackai-trigger#414]
**Is your feature request related to a problem? Please describe.**
When requesting a PR's all warnings reported buy lint should be fixed/removed. Yet the warnings are not very visible. 

**Describe the solution you'd like**
To save time on manual checks I suggest lint to be configured to fail the build if warnings are present. 

**Describe alternatives you've considered**

**Additional context**

**Comment by danecreekphotography** [comment]
Closing old issues.
