### ISSUE TITLE
That the properties of a trigger can be changed via MQTT

### ISSUE THREAD

**Issue by jbolanosg** [danecreekphotography/node-deepstackai-trigger#415]
It would be very useful if in specific circumstances a trigger can be enabled or disabled or properties such as: cooldownTime, threshold and others can be changed. If the triggers are reinitialized, they start with the properties configured in the trigger.json.

**Comment by danecreekphotography** [comment]
It seems plausible to add something that would allow re-configuring existing triggers by sending a message to a topic like `triggername/settings`, but persisting those settings between launches of the Docker container would be a pretty major change and one I'm unlikely to tackle any time soon.

What's the scenario you're trying to accomplish?

**Comment by danecreekphotography** [comment]
Closing old issues.
