### ISSUE TITLE
AI System Status is showing disconnected every time after rebooting Home Assistant

### ISSUE THREAD

**Issue by reesion** [danecreekphotography/node-deepstackai-trigger#423]
**What trouble are you having?**
AI System Status (binary_sensor.ai_system_status) is showing disconnected every time after rebooting Home Assistant. I will need to restart the ai-trigger container to bring the status back to "connected"

**Have you tried with the sample files?**
No
**Have you tried the steps in the troubleshooting guide?**

https://github.com/danecreekphotography/node-deepstackai-trigger/wiki/Troubleshooting
Ye

**Log entries**

Please copy and paste all the log messages from the Docker output

**Installation details**

 - OS: [e.g. Mac, Windows 10] 
   Debian
 - Docker setup [e.g. sample docker-compose.yaml, Portainer, UnRAID, etc]
 Portainer with docker-compose.yaml

**Additional context**

**Comment by danecreekphotography** [comment]
Do you have `retain` set to `true` in the MQTT section of your settings file?

**Comment by reesion** [comment]
No. I didn't have that set but I have now set it and that seems to fix the issue. 
Thank you very much.

**Comment by danecreekphotography** [comment]
Thinking about this a bit more I don't think this is a real fix. The system should be sending "online" MQTT messages periodically, more frequently than the LWT message. I'll think about this a bit more.

**Comment by linuxkidd** [comment]
Agreed, the 'retain' is not a good fix.  I've had lingering trigger events in MQTT ( BlueIris/admin ) with 'retain' that cause BI to crash during start-up.  Took me a good long while to find that issue.

**Comment by danecreekphotography** [comment]
Notes to myself:

Currently online is published here:

https://github.com/danecreekphotography/node-deepstackai-trigger/blob/d1a11baa957f1956279d1afe154b78132fd34307/src/main.ts#L122

This should probably move inside MqttManager and just be done inside a timer that keeps firing every whatever seconds. If I wanted to get fancy the interval could get specified in the settings file.

**Comment by danecreekphotography** [comment]
Ok I have a build for you to try @reesion. Change your Docker config so instead of pulling `latest` it pulls `issue423`. Then use some sort of MQTT tool (if you are on Windows the MQTT Explorer app from Windows Store is amazing) to clear out the retained status message.

Then fire up everything. You should see a new "online" message pop in every 60 seconds. If you kill HA and restart it will pick up the proper online status at the next health message arrival (within 60 seconds).

**Comment by reesion** [comment]
Have just tested this and it works.

![image](https://user-images.githubusercontent.com/53692597/108131320-34d3c100-7105-11eb-80e4-37ae018bbca5.png)

**Comment by danecreekphotography** [comment]
Noice!!! Thanks. I'll get this released as v5.8.0 later today and let you know when it's out so you can flip back to `latest`.

**Comment by danecreekphotography** [comment]
This is now deployed. You can switch your docker tag back to `latest` @reesion .

**Comment by reesion** [comment]
Thank you
