### ISSUE TITLE
Fix typo in mqtt manager log message

### ISSUE THREAD

**Issue by danecreekphotography** [danecreekphotography/node-deepstackai-trigger#48]
https://github.com/danecreekphotography/node-deepstackai-trigger/blob/d29d03dbd5c6a1454de9af0ce7870f401281d94b/src/handlers/mqttManager/MqttManager.ts#L130

This should say MQTT not trigger.

**Comment by mmbhatk** [comment]
Could you please assign this issue to me? Since I don't have write access to the repo, I am not able to do so.

**Comment by danecreekphotography** [comment]
I've invited you as a collaborator, I believe that'll give you the necessary access to assign the issue to yourself. Thanks for your patience, I'm still working through all the git fun :)

**Comment by mmbhatk** [comment]
No problem. Thank you :)
