### ISSUE TITLE
Replace some try/catch blocks with .catch()

### ISSUE THREAD

**Issue by danecreekphotography** [danecreekphotography/node-deepstackai-trigger#68]
There are quite a few places in the code where try/catch blocks with `let` variables just outside the try statement can be replaced with the cleaner `.catch()` method for handling errors.

**Comment by mattbho** [comment]
I can take this over for ya!

**Comment by mattbho** [comment]
Not sure if I have access to assign the issue to myself though. Can you add me as a contributer?

**Comment by danecreekphotography** [comment]
Yup, will do. Not sure how many places in the code need it done but it's quite a few!

**Comment by danecreekphotography** [comment]
@mattbho be aware I have a pretty big merge coming tonight for #37. You may want to hang tight until that's in to reduce the amount of merge nonsense you'll have to deal with.

**Comment by mattbho** [comment]
Sounds good! I'll probably have a PR for you to review by tomorrow EOD

**Comment by danecreekphotography** [comment]
Fun times! Thank you.

**Comment by danecreekphotography** [comment]
Changes for #37 are merged. I had some issues running `npm version`, not sure what your dev environment is but if you are using the Remote - Containers setup you'll need to use `npm version --unsafe-perm`. See #72.

**Comment by mattbho** [comment]
Sounds good! I'll keep you updated.
