### ISSUE TITLE
Difference in versions specified

### ISSUE THREAD

**Issue by mmbhatk** [danecreekphotography/node-deepstackai-trigger#82]
In [CHANGELOG.md](https://github.com/danecreekphotography/node-deepstackai-trigger/blob/master/CHANGELOG.md), the latest version specified is 1.1.3.
However, according to [package.json](https://github.com/danecreekphotography/node-deepstackai-trigger/blob/master/package.json) and [package-lock.json](https://github.com/danecreekphotography/node-deepstackai-trigger/blob/master/package-lock.json), the current version is 1.1.2.

When I run 'npm version patch', it creates the version 1.1.3. Just wanted to clarify if the current version needs to be 1.1.3 as I am creating a pull request for an updated version.

**Comment by danecreekphotography** [comment]
Good catch. I think this happened when I hit #72. Fixing now.
